insert into collection (review_id, review_text, collection_id, user_id) values (1, 'velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo', 41, 10);
insert into collection (review_id, review_text, collection_id, user_id) values (2, 'tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi', 45, 11);
insert into collection (review_id, review_text, collection_id, user_id) values (3, 'in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin', 51, 5);
insert into collection (review_id, review_text, collection_id, user_id) values (4, 'nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula', 23, 3);
insert into collection (review_id, review_text, collection_id, user_id) values (5, 'justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales', 13, 16);
insert into collection (review_id, review_text, collection_id, user_id) values (6, 'adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede', 41, 11);
insert into collection (review_id, review_text, collection_id, user_id) values (7, 'sit amet eleifend pede libero quis orci nullam molestie nibh in', 2, 12);
insert into collection (review_id, review_text, collection_id, user_id) values (8, 'proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula', 44, 16);
insert into collection (review_id, review_text, collection_id, user_id) values (9, 'vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue', 51, 7);
insert into collection (review_id, review_text, collection_id, user_id) values (10, 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque', 53, 11);
insert into collection (review_id, review_text, collection_id, user_id) values (11, 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis', 13, 15);
insert into collection (review_id, review_text, collection_id, user_id) values (12, 'justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut', 60, 1);
insert into collection (review_id, review_text, collection_id, user_id) values (13, 'orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis', 18, 6);
insert into collection (review_id, review_text, collection_id, user_id) values (14, 'nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus', 51, 4);
insert into collection (review_id, review_text, collection_id, user_id) values (15, 'semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et', 5, 15);
insert into collection (review_id, review_text, collection_id, user_id) values (16, 'quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis', 34, 12);
insert into collection (review_id, review_text, collection_id, user_id) values (17, 'posuere nonummy integer non velit donec diam neque vestibulum eget', 11, 13);
insert into collection (review_id, review_text, collection_id, user_id) values (18, 'pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus', 52, 7);
insert into collection (review_id, review_text, collection_id, user_id) values (19, 'sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor', 5, 6);
insert into collection (review_id, review_text, collection_id, user_id) values (20, 'orci eget orci vehicula condimentum curabitur in libero ut massa volutpat', 1, 2);
insert into collection (review_id, review_text, collection_id, user_id) values (21, 'at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae', 47, 20);
insert into collection (review_id, review_text, collection_id, user_id) values (22, 'arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula', 51, 5);
insert into collection (review_id, review_text, collection_id, user_id) values (23, 'tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', 8, 10);
insert into collection (review_id, review_text, collection_id, user_id) values (24, 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi', 11, 19);
insert into collection (review_id, review_text, collection_id, user_id) values (25, 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu', 59, 16);
insert into collection (review_id, review_text, collection_id, user_id) values (26, 'tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus', 14, 15);
insert into collection (review_id, review_text, collection_id, user_id) values (27, 'nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat', 60, 2);
insert into collection (review_id, review_text, collection_id, user_id) values (28, 'orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum', 41, 13);
insert into collection (review_id, review_text, collection_id, user_id) values (29, 'quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer', 24, 6);
insert into collection (review_id, review_text, collection_id, user_id) values (30, 'vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero', 58, 12);
insert into collection (review_id, review_text, collection_id, user_id) values (31, 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes', 35, 12);
insert into collection (review_id, review_text, collection_id, user_id) values (32, 'elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum', 28, 1);
insert into collection (review_id, review_text, collection_id, user_id) values (33, 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi', 5, 15);
insert into collection (review_id, review_text, collection_id, user_id) values (34, 'pede justo lacinia eget tincidunt eget tempus vel pede morbi', 36, 6);
insert into collection (review_id, review_text, collection_id, user_id) values (35, 'quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere', 46, 5);
insert into collection (review_id, review_text, collection_id, user_id) values (36, 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus', 27, 12);
insert into collection (review_id, review_text, collection_id, user_id) values (37, 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante', 15, 18);
insert into collection (review_id, review_text, collection_id, user_id) values (38, 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis', 50, 11);
insert into collection (review_id, review_text, collection_id, user_id) values (39, 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget', 8, 20);
insert into collection (review_id, review_text, collection_id, user_id) values (40, 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non', 2, 7);
insert into collection (review_id, review_text, collection_id, user_id) values (41, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus', 6, 3);
insert into collection (review_id, review_text, collection_id, user_id) values (42, 'nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum', 8, 3);
insert into collection (review_id, review_text, collection_id, user_id) values (43, 'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien', 18, 12);
insert into collection (review_id, review_text, collection_id, user_id) values (44, 'duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede', 19, 5);
insert into collection (review_id, review_text, collection_id, user_id) values (45, 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit', 12, 13);
insert into collection (review_id, review_text, collection_id, user_id) values (46, 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet', 25, 5);
insert into collection (review_id, review_text, collection_id, user_id) values (47, 'id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio', 11, 13);
insert into collection (review_id, review_text, collection_id, user_id) values (48, 'ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at', 7, 20);
insert into collection (review_id, review_text, collection_id, user_id) values (49, 'eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla', 22, 20);
insert into collection (review_id, review_text, collection_id, user_id) values (50, 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut', 44, 14);
insert into collection (review_id, review_text, collection_id, user_id) values (51, 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur', 21, 17);
insert into collection (review_id, review_text, collection_id, user_id) values (52, 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien', 18, 8);
insert into collection (review_id, review_text, collection_id, user_id) values (53, 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros', 51, 17);
insert into collection (review_id, review_text, collection_id, user_id) values (54, 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in', 27, 6);
insert into collection (review_id, review_text, collection_id, user_id) values (55, 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum', 23, 19);
insert into collection (review_id, review_text, collection_id, user_id) values (56, 'tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero', 28, 5);
insert into collection (review_id, review_text, collection_id, user_id) values (57, 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 42, 14);
insert into collection (review_id, review_text, collection_id, user_id) values (58, 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque', 52, 19);
insert into collection (review_id, review_text, collection_id, user_id) values (59, 'at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur', 7, 19);
insert into collection (review_id, review_text, collection_id, user_id) values (60, 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed', 59, 12);
