insert into review (review_id, review_text, collection_id, user_id) values (1, 'tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi', 55, 13);
insert into review (review_id, review_text, collection_id, user_id) values (2, 'sed magna at nunc commodo placerat praesent blandit nam nulla integer pede', 60, 8);
insert into review (review_id, review_text, collection_id, user_id) values (3, 'tincidunt lacus at velit vivamus vel nulla eget eros elementum', 3, 9);
insert into review (review_id, review_text, collection_id, user_id) values (4, 'varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci', 45, 1);
insert into review (review_id, review_text, collection_id, user_id) values (5, 'sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut', 2, 18);
insert into review (review_id, review_text, collection_id, user_id) values (6, 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', 35, 20);
insert into review (review_id, review_text, collection_id, user_id) values (7, 'nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget', 17, 18);
insert into review (review_id, review_text, collection_id, user_id) values (8, 'praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula', 54, 4);
insert into review (review_id, review_text, collection_id, user_id) values (9, 'in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis', 35, 18);
insert into review (review_id, review_text, collection_id, user_id) values (10, 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum', 53, 14);
insert into review (review_id, review_text, collection_id, user_id) values (11, 'ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque', 20, 16);
insert into review (review_id, review_text, collection_id, user_id) values (12, 'sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper', 7, 1);
insert into review (review_id, review_text, collection_id, user_id) values (13, 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis', 33, 4);
insert into review (review_id, review_text, collection_id, user_id) values (14, 'donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend', 57, 15);
insert into review (review_id, review_text, collection_id, user_id) values (15, 'nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula', 58, 4);
insert into review (review_id, review_text, collection_id, user_id) values (16, 'aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero', 4, 14);
insert into review (review_id, review_text, collection_id, user_id) values (17, 'diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat', 60, 15);
insert into review (review_id, review_text, collection_id, user_id) values (18, 'ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent', 16, 1);
insert into review (review_id, review_text, collection_id, user_id) values (19, 'proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in', 16, 4);
insert into review (review_id, review_text, collection_id, user_id) values (20, 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', 60, 6);
insert into review (review_id, review_text, collection_id, user_id) values (21, 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede', 31, 7);
insert into review (review_id, review_text, collection_id, user_id) values (22, 'cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras', 53, 19);
insert into review (review_id, review_text, collection_id, user_id) values (23, 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet', 55, 1);
insert into review (review_id, review_text, collection_id, user_id) values (24, 'libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit', 23, 7);
insert into review (review_id, review_text, collection_id, user_id) values (25, 'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis', 17, 6);
insert into review (review_id, review_text, collection_id, user_id) values (26, 'ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam', 43, 8);
insert into review (review_id, review_text, collection_id, user_id) values (27, 'sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus', 7, 16);
insert into review (review_id, review_text, collection_id, user_id) values (28, 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus', 29, 16);
insert into review (review_id, review_text, collection_id, user_id) values (29, 'cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit', 18, 13);
insert into review (review_id, review_text, collection_id, user_id) values (30, 'lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra', 25, 2);
insert into review (review_id, review_text, collection_id, user_id) values (31, 'eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', 25, 19);
insert into review (review_id, review_text, collection_id, user_id) values (32, 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed', 43, 11);
insert into review (review_id, review_text, collection_id, user_id) values (33, 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit', 21, 4);
insert into review (review_id, review_text, collection_id, user_id) values (34, 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui', 29, 7);
insert into review (review_id, review_text, collection_id, user_id) values (35, 'ullamcorper augue a suscipit nulla elit ac nulla sed vel', 53, 5);
insert into review (review_id, review_text, collection_id, user_id) values (36, 'quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed', 18, 18);
insert into review (review_id, review_text, collection_id, user_id) values (37, 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh', 53, 2);
insert into review (review_id, review_text, collection_id, user_id) values (38, 'justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem', 11, 4);
insert into review (review_id, review_text, collection_id, user_id) values (39, 'nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh', 28, 5);
insert into review (review_id, review_text, collection_id, user_id) values (40, 'nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa', 58, 10);
insert into review (review_id, review_text, collection_id, user_id) values (41, 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla', 20, 13);
insert into review (review_id, review_text, collection_id, user_id) values (42, 'interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus', 41, 3);
insert into review (review_id, review_text, collection_id, user_id) values (43, 'morbi non lectus aliquam sit amet diam in magna bibendum imperdiet', 21, 2);
insert into review (review_id, review_text, collection_id, user_id) values (44, 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in', 33, 16);
insert into review (review_id, review_text, collection_id, user_id) values (45, 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis', 34, 6);
insert into review (review_id, review_text, collection_id, user_id) values (46, 'velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam', 36, 2);
insert into review (review_id, review_text, collection_id, user_id) values (47, 'consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo', 57, 8);
insert into review (review_id, review_text, collection_id, user_id) values (48, 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam', 34, 20);
insert into review (review_id, review_text, collection_id, user_id) values (49, 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper', 12, 9);
insert into review (review_id, review_text, collection_id, user_id) values (50, 'at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum', 26, 17);
insert into review (review_id, review_text, collection_id, user_id) values (51, 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel', 58, 4);
insert into review (review_id, review_text, collection_id, user_id) values (52, 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque', 33, 3);
insert into review (review_id, review_text, collection_id, user_id) values (53, 'id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et', 42, 9);
insert into review (review_id, review_text, collection_id, user_id) values (54, 'hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer', 33, 19);
insert into review (review_id, review_text, collection_id, user_id) values (55, 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna', 43, 11);
insert into review (review_id, review_text, collection_id, user_id) values (56, 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 32, 15);
insert into review (review_id, review_text, collection_id, user_id) values (57, 'tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl', 27, 10);
insert into review (review_id, review_text, collection_id, user_id) values (58, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 55, 7);
insert into review (review_id, review_text, collection_id, user_id) values (59, 'condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales', 57, 7);
insert into review (review_id, review_text, collection_id, user_id) values (60, 'ut erat curabitur gravida nisi at nibh in hac habitasse platea', 32, 2);
