insert into song (song_id, song_name, song_desc, song_artist) values (1, 'Vulture, lappet-faced', 'Release Left Metacarpal, Open Approach', 'Rowan Landrean');
insert into song (song_id, song_name, song_desc, song_artist) values (2, 'Iguana, land', 'Resection of Scrotum, Open Approach', 'Erroll Erlam');
insert into song (song_id, song_name, song_desc, song_artist) values (3, 'Lark, horned', 'Bypass Portal Vein to L Renal Vein w Synth Sub, Perc Endo', 'Ignaz Soaper');
insert into song (song_id, song_name, song_desc, song_artist) values (4, 'Common zebra', 'Revision of Synthetic Substitute in Right Ear, Perc Approach', 'Katusha Boag');
insert into song (song_id, song_name, song_desc, song_artist) values (5, 'Screamer, crested', 'Revision of Autol Sub in Lum Disc, Perc Approach', 'Francyne Massei');
insert into song (song_id, song_name, song_desc, song_artist) values (6, 'Wattled crane', 'Dilation of L Com Carotid with 3 Drug-elut, Open Approach', 'Ramsey Sybe');
insert into song (song_id, song_name, song_desc, song_artist) values (7, 'Lizard, collared', 'Revision of Radioactive Element in Low Back, Extern Approach', 'Vin Godmar');
insert into song (song_id, song_name, song_desc, song_artist) values (8, 'Dolphin, striped', 'Supplement Right Epididymis with Nonaut Sub, Open Approach', 'Deborah Tosdevin');
insert into song (song_id, song_name, song_desc, song_artist) values (9, 'Cobra (unidentified)', 'Repair Left Lesser Saphenous Vein, Open Approach', 'Rich Comino');
insert into song (song_id, song_name, song_desc, song_artist) values (10, 'Hornbill, leadbeateri''s ground', 'Transfuse Autol Cord Bld Stem Cell in Periph Art, Open', 'Rubina Rickard');
insert into song (song_id, song_name, song_desc, song_artist) values (11, 'Skimmer, four-spotted', 'Repair Right Internal Jugular Vein, Percutaneous Approach', 'Clio Tolotti');
insert into song (song_id, song_name, song_desc, song_artist) values (12, 'Eagle, pallas''s fish', 'CT Scan of L Pulm Vein using H Osm Contrast, Unenh, Enhance', 'Edyth Buckthought');
insert into song (song_id, song_name, song_desc, song_artist) values (13, 'Margay', 'HDR Brachytherapy of Peripheral Nerve using Palladium 103', 'Genny Donaghy');
insert into song (song_id, song_name, song_desc, song_artist) values (14, 'Crane, black-crowned', 'Change Drainage Device in Upper Bone, External Approach', 'Pietrek Bolderstone');
insert into song (song_id, song_name, song_desc, song_artist) values (15, 'African elephant', 'Transfer Radial Nerve to Ulnar Nerve, Perc Endo Approach', 'Marcos Burel');
insert into song (song_id, song_name, song_desc, song_artist) values (16, 'Skua, long-tailed', 'Occlusion L Up Lobe Bronc w Intralum Dev, Open', 'Shayla Marnane');
insert into song (song_id, song_name, song_desc, song_artist) values (17, 'Trotter, lily', 'Removal of Synth Sub from R Patella, Perc Approach', 'Aurilia Benito');
insert into song (song_id, song_name, song_desc, song_artist) values (18, 'Worm snake (unidentified)', 'Insertion of Monitor Dev into Small Intest, Via Opening', 'Chloette Galbreth');
insert into song (song_id, song_name, song_desc, song_artist) values (19, 'Sheep, american bighorn', 'Replace of Pulm Trunk with Zooplastic, Perc Endo Approach', 'Pierrette Arpe');
insert into song (song_id, song_name, song_desc, song_artist) values (20, 'Dog, raccoon', 'Supplement Left Breast with Autol Sub, Open Approach', 'Royall Mackrill');
insert into song (song_id, song_name, song_desc, song_artist) values (21, 'Short-beaked echidna', 'Fluoroscopy of Lumbar Facet Joint(s)', 'Dollie Gather');
insert into song (song_id, song_name, song_desc, song_artist) values (22, 'Southern right whale', 'Insertion of Infusion Dev into R Temporal Art, Perc Approach', 'Loutitia Doorbar');
insert into song (song_id, song_name, song_desc, song_artist) values (23, 'Chipmunk, least', 'Release Cerebral Ventricle, Percutaneous Endoscopic Approach', 'Albert Wretham');
insert into song (song_id, song_name, song_desc, song_artist) values (24, 'Colobus, white-mantled', 'Bypass L Com Iliac Art to B Renal A, Perc Endo Approach', 'Lionello Utting');
insert into song (song_id, song_name, song_desc, song_artist) values (25, 'Sloth, two-toed tree', 'Destruction of Left External Ear, Perc Endo Approach', 'Lilah Ellick');
insert into song (song_id, song_name, song_desc, song_artist) values (26, 'Jacana, african', 'Restriction of Middle Esophagus, Percutaneous Approach', 'Layne Maus');
insert into song (song_id, song_name, song_desc, song_artist) values (27, 'Stilt, black-winged', 'Resection of Pelvis Lymphatic, Open Approach', 'Letitia Dicks');
insert into song (song_id, song_name, song_desc, song_artist) values (28, 'Northern elephant seal', 'Alteration of Upper Jaw with Autol Sub, Perc Endo Approach', 'Robina Storrier');
insert into song (song_id, song_name, song_desc, song_artist) values (29, 'Gulls (unidentified)', 'Bypass L Int Iliac Art to B Femor A, Perc Endo Approach', 'Pammy Cracker');
insert into song (song_id, song_name, song_desc, song_artist) values (30, 'Asian red fox', 'Revise of Synth Sub in Vagina & Cul-de-sac, Extern Approach', 'Hyatt Gouth');
insert into song (song_id, song_name, song_desc, song_artist) values (31, 'Lizard, mexican beaded', 'Insertion of Infusion Device into R Colic Art, Open Approach', 'Ailyn Keveren');
insert into song (song_id, song_name, song_desc, song_artist) values (32, 'Crane, sarus', 'Reposition Left Hip Joint, Percutaneous Endoscopic Approach', 'Fabiano Fenty');
insert into song (song_id, song_name, song_desc, song_artist) values (33, 'Red-shouldered glossy starling', 'Fusion 2-7 T Jt w Nonaut Sub, Post Appr P Col, Perc Endo', 'Legra Yantsev');
insert into song (song_id, song_name, song_desc, song_artist) values (34, 'Indian star tortoise', 'Revision of Intraluminal Device in Left Ear, Perc Approach', 'George Biaggi');
insert into song (song_id, song_name, song_desc, song_artist) values (35, 'Little grebe', 'Revision of Diaphragmatic Pacemaker Lead in Diaphragm, Endo', 'Petey Candish');
insert into song (song_id, song_name, song_desc, song_artist) values (36, 'Eland, common', 'Excision of Ileocecal Valve, Endo, Diagn', 'Fidela McCann');
insert into song (song_id, song_name, song_desc, song_artist) values (37, 'Southern elephant seal', 'Revision of Nonaut Sub in Cerv Disc, Perc Endo Approach', 'Valma Grombridge');
insert into song (song_id, song_name, song_desc, song_artist) values (38, 'Magistrate black colobus', 'Supplement L Femoral Region w Synth Sub, Perc Endo', 'Shannon Bunker');
insert into song (song_id, song_name, song_desc, song_artist) values (39, 'Arctic fox', 'Extirpate matter from L Verteb Art, Bifurc, Perc Endo', 'Delphinia Fitzsymonds');
insert into song (song_id, song_name, song_desc, song_artist) values (40, 'House sparrow', 'Supplement Innom Art with Autol Sub, Perc Endo Approach', 'Anatol Everiss');
insert into song (song_id, song_name, song_desc, song_artist) values (41, 'Capuchin, brown', 'Coordination/Dexterity Treatment of Musculosk Up Back/UE', 'Karmen MacGray');
insert into song (song_id, song_name, song_desc, song_artist) values (42, 'Hoary marmot', 'Release Right Shoulder Tendon, Percutaneous Approach', 'Minni Eyree');
insert into song (song_id, song_name, song_desc, song_artist) values (43, 'Southern hairy-nosed wombat', 'Monitoring of Arterial Pressure, Pulmonary, Open Approach', 'Janaye Mariel');
insert into song (song_id, song_name, song_desc, song_artist) values (44, 'Old world fruit bat (unidentified)', 'Excision of R Metacarpophal Jt, Perc Endo Approach, Diagn', 'Osmond Scrivener');
insert into song (song_id, song_name, song_desc, song_artist) values (45, 'Rhesus macaque', 'Excision of Hard Palate, External Approach', 'Jacintha Taillard');
insert into song (song_id, song_name, song_desc, song_artist) values (46, 'Northern phalarope', 'Plain Radiography of All Teeth', 'Goldi Farncombe');
insert into song (song_id, song_name, song_desc, song_artist) values (47, 'White-mantled colobus', 'Bypass R Kidney Pelvis to R Kid Pelv w Synth Sub, Open', 'Geralda Osan');
insert into song (song_id, song_name, song_desc, song_artist) values (48, 'White-necked raven', 'Dilate R Foot Art, Bifurc, w 3 Intralum Dev, Perc', 'Stavro Chicchelli');
insert into song (song_id, song_name, song_desc, song_artist) values (49, 'Jackal, black-backed', 'Removal of Autol Sub from R Ear, Perc Approach', 'Conni Applewhite');
insert into song (song_id, song_name, song_desc, song_artist) values (50, 'Anaconda (unidentified)', 'Excision of Left Axilla, Percutaneous Approach', 'Bil Clapston');
insert into song (song_id, song_name, song_desc, song_artist) values (51, 'Royal tern', 'Replacement of R Hand Art with Nonaut Sub, Open Approach', 'Guthrie Tewkesbury');
insert into song (song_id, song_name, song_desc, song_artist) values (52, 'Kongoni', 'Excision of Left Vas Deferens, Perc Endo Approach, Diagn', 'Nonna Chadwyck');
insert into song (song_id, song_name, song_desc, song_artist) values (53, 'Masked booby', 'Reattachment of Right Middle Lung Lobe, Open Approach', 'Leoine Bowbrick');
insert into song (song_id, song_name, song_desc, song_artist) values (54, 'Impala', 'Drainage of Left Elbow Joint, Open Approach', 'Berkly Riseborough');
insert into song (song_id, song_name, song_desc, song_artist) values (55, 'Roadrunner, greater', 'Dilate R Ext Carotid w 4+ Intralum Dev, Perc Endo', 'Dosi Iczokvitz');
insert into song (song_id, song_name, song_desc, song_artist) values (56, 'European wild cat', 'Replacement of L Foot Skin with Synth Sub, Extern Approach', 'Farand Alred');
insert into song (song_id, song_name, song_desc, song_artist) values (57, 'Red-tailed wambenger', 'Supplement R Ankle with Synth Sub, Perc Endo Approach', 'Llewellyn Pacheco');
insert into song (song_id, song_name, song_desc, song_artist) values (58, 'Arctic ground squirrel', 'Beam Radiation of Back Skin using Electrons, Intraoperative', 'Yancy Bohman');
insert into song (song_id, song_name, song_desc, song_artist) values (59, 'Mocking cliffchat', 'Release Multiple Parathyroid Glands, Perc Endo Approach', 'Christoph Sinson');
insert into song (song_id, song_name, song_desc, song_artist) values (60, 'Francolin, coqui', 'Removal of Synth Sub from L Metacarpocarp Jt, Open Approach', 'Martie Martin');
insert into song (song_id, song_name, song_desc, song_artist) values (61, 'Peccary, white-lipped', 'Insertion of Other Device into Left Upper Leg, Perc Approach', 'Emmalee Reckhouse');
insert into song (song_id, song_name, song_desc, song_artist) values (62, 'Legaan, ground', 'Excision of Left Metacarpocarpal Joint, Perc Approach, Diagn', 'Georges Stairmand');
insert into song (song_id, song_name, song_desc, song_artist) values (63, 'Gull, lava', 'Dilation of R Hand Art with 4+ Intralum Dev, Open Approach', 'Jerome Andriesse');
insert into song (song_id, song_name, song_desc, song_artist) values (64, 'Frogmouth, tawny', 'LDR Brachytherapy of Salivary Gland using Iridium 192', 'Davin Valiant');
insert into song (song_id, song_name, song_desc, song_artist) values (65, 'Capuchin, brown', 'Dilate of L Ext Carotid with 4 Drug-elut, Perc Endo Approach', 'Selie Morrel');
insert into song (song_id, song_name, song_desc, song_artist) values (66, 'Crimson-breasted shrike', 'Supplement Left Toe Phalanx with Nonaut Sub, Open Approach', 'Marcie Heddon');
insert into song (song_id, song_name, song_desc, song_artist) values (67, 'African jacana', 'Restrict R Inqnl Lymph w Intralum Dev, Perc Endo', 'Querida De Blase');
insert into song (song_id, song_name, song_desc, song_artist) values (68, 'Impala', 'Drainage of Glossopharyngeal Nerve, Perc Approach, Diagn', 'Pam Heatly');
insert into song (song_id, song_name, song_desc, song_artist) values (69, 'Cat, long-tailed spotted', 'Supplement L Sacroiliac Jt with Synth Sub, Perc Approach', 'Dasya Stockdale');
insert into song (song_id, song_name, song_desc, song_artist) values (70, 'Common brushtail possum', 'Bypass 3 Cor Art from L Int Mammary, Perc Endo Approach', 'Bettye Capstaff');
insert into song (song_id, song_name, song_desc, song_artist) values (71, 'Gull, pacific', 'Drainage of Abdominal Sympathetic Nerve, Perc Endo Approach', 'Saul Shillan');
insert into song (song_id, song_name, song_desc, song_artist) values (72, 'Northern phalarope', 'Dilate L Radial Art, Bifurc, w 3 Drug-elut, Open', 'Jillayne Penhall');
insert into song (song_id, song_name, song_desc, song_artist) values (73, 'Crimson-breasted shrike', 'Extirpation of Matter from Left Lacrimal Duct, Perc Approach', 'Marybelle Kees');
insert into song (song_id, song_name, song_desc, song_artist) values (74, 'Ringtail', 'Beam Radiation of Brain using Heavy Particles (Protons,Ions)', 'Melisent Latter');
insert into song (song_id, song_name, song_desc, song_artist) values (75, 'Fox, arctic', 'Supplement Left Elbow Joint with Synth Sub, Open Approach', 'Dar Dunnan');
insert into song (song_id, song_name, song_desc, song_artist) values (76, 'Galapagos albatross', 'Immobilization of Left Upper Arm using Splint', 'Odette Curado');
insert into song (song_id, song_name, song_desc, song_artist) values (77, 'Cat, miner''s', 'Remove Infusion Dev from Scrotum & Tunica, Perc Endo', 'Jehanna Gilbody');
insert into song (song_id, song_name, song_desc, song_artist) values (78, 'American bighorn sheep', 'Supplement L Popl Art with Synth Sub, Perc Endo Approach', 'Thaddus Glasner');
insert into song (song_id, song_name, song_desc, song_artist) values (79, 'Eastern diamondback rattlesnake', 'Removal of Cast on Right Lower Arm', 'Fan Kingzett');
insert into song (song_id, song_name, song_desc, song_artist) values (80, 'Squirrel, smith''s bush', 'Replacement of Mitral Valve with Synth Sub, Perc Approach', 'Victoir Blyde');
insert into song (song_id, song_name, song_desc, song_artist) values (81, 'Numbat', 'Destruction of Buttock Skin, Multiple, External Approach', 'Dorene Dance');
insert into song (song_id, song_name, song_desc, song_artist) values (82, 'Eastern quoll', 'Skin and Breast, Revision', 'Winthrop Samet');
insert into song (song_id, song_name, song_desc, song_artist) values (83, 'Gull, pacific', 'Drainage of Vagina, Percutaneous Endoscopic Approach', 'Rhodie Ludwikiewicz');
insert into song (song_id, song_name, song_desc, song_artist) values (84, 'Fox, arctic', 'Drainage of R Ant Tib Art, Perc Approach, Diagn', 'Claretta Natwick');
insert into song (song_id, song_name, song_desc, song_artist) values (85, 'Mongoose, yellow', 'Supplement Optic Nerve with Autol Sub, Perc Approach', 'Carey Mackrell');
insert into song (song_id, song_name, song_desc, song_artist) values (86, 'Duck, comb', 'Dilate L Thyroid Art, Bifurc, w Drug-elut Intra, Perc Endo', 'Lura Enefer');
insert into song (song_id, song_name, song_desc, song_artist) values (87, 'Blackish oystercatcher', 'Excision of Trochlear Nerve, Open Approach, Diagnostic', 'Jobyna Bowich');
insert into song (song_id, song_name, song_desc, song_artist) values (88, 'Devil, tasmanian', 'Dilate Innom Art, Bifurc, w 4+ Intralum Dev, Perc Endo', 'Merrilee Vedeneev');
insert into song (song_id, song_name, song_desc, song_artist) values (89, 'Giant heron', 'Removal of Synth Sub from Thor Disc, Perc Approach', 'Malissia Ashmore');
insert into song (song_id, song_name, song_desc, song_artist) values (90, 'Red phalarope', 'Revision of Synth Sub in L Metacarpal, Open Approach', 'Grace Ivanov');
insert into song (song_id, song_name, song_desc, song_artist) values (91, 'Greater kudu', 'Dilation of Azygos Vein, Open Approach', 'Dniren Priddle');
insert into song (song_id, song_name, song_desc, song_artist) values (92, 'Greater rhea', 'Reposition Phrenic Nerve, Percutaneous Approach', 'Mose Poone');
insert into song (song_id, song_name, song_desc, song_artist) values (93, 'Kookaburra, laughing', 'Drainage of Inferior Mesenteric Artery, Perc Endo Approach', 'Chaunce Brunstan');
insert into song (song_id, song_name, song_desc, song_artist) values (94, 'Raccoon, crab-eating', 'Occlusion of Aortic Lymphatic, Perc Endo Approach', 'Stanislas Trenaman');
insert into song (song_id, song_name, song_desc, song_artist) values (95, 'Yellow-billed stork', 'Restrict L Femor Vein w Extralum Dev, Perc Endo', 'Walden Chate');
insert into song (song_id, song_name, song_desc, song_artist) values (96, 'Squirrel, antelope ground', 'Destruction of Right Temporomandibular Joint, Perc Approach', 'Basia McGookin');
insert into song (song_id, song_name, song_desc, song_artist) values (97, 'Common brushtail possum', 'Release Right Kidney, Via Natural or Artificial Opening', 'Rooney Groneway');
insert into song (song_id, song_name, song_desc, song_artist) values (98, 'South American meadowlark (unidentified)', 'Insertion of Hybrid Ext Fix into R Up Femur, Perc Approach', 'Gianni Burlay');
insert into song (song_id, song_name, song_desc, song_artist) values (99, 'Swallow-tail gull', 'Drainage of Portal Vein with Drainage Device, Perc Approach', 'Myrilla Bauldry');
insert into song (song_id, song_name, song_desc, song_artist) values (100, 'Tasmanian devil', 'Revision of Autol Sub in L Up Extrem, Open Approach', 'Shem Roll');
insert into song (song_id, song_name, song_desc, song_artist) values (101, 'Roe deer', 'Drainage of Intracran Art with Drain Dev, Perc Approach', 'Cherye Doy');
insert into song (song_id, song_name, song_desc, song_artist) values (102, 'Baboon, savanna', 'Release Left Hand Vein, Open Approach', 'Fay Reinbeck');
insert into song (song_id, song_name, song_desc, song_artist) values (103, 'Bobcat', 'Removal of Brace on Right Lower Extremity', 'Bianka Calender');
insert into song (song_id, song_name, song_desc, song_artist) values (104, 'North American river otter', 'Revision of Radioact Elem in Low Jaw, Perc Endo Approach', 'Artemis Compford');
insert into song (song_id, song_name, song_desc, song_artist) values (105, 'Nutcracker, clark''s', 'Release Left Lesser Saphenous Vein, Percutaneous Approach', 'Karine Pinn');
insert into song (song_id, song_name, song_desc, song_artist) values (106, 'Crane, black-crowned', 'Occlusion R Int Carotid w Bioact Intralum, Perc', 'Irena Bowie');
insert into song (song_id, song_name, song_desc, song_artist) values (107, 'Bontebok', 'Beam Radiation of Pelvis Lymphatics using Heavy Particles', 'Bessie Medhurst');
insert into song (song_id, song_name, song_desc, song_artist) values (108, 'Common long-nosed armadillo', 'Extirpation of Matter from L Sperm Cord, Open Approach', 'Gracia Benedicte');
insert into song (song_id, song_name, song_desc, song_artist) values (109, 'Great skua', 'Occlusion of Right Vertebral Vein, Perc Endo Approach', 'Abbie Cancott');
insert into song (song_id, song_name, song_desc, song_artist) values (110, 'Crane, black-crowned', 'Inspection of Heart, Percutaneous Approach', 'Marie McGrail');
insert into song (song_id, song_name, song_desc, song_artist) values (111, 'Common ringtail', 'Repair Abdomen Subcutaneous Tissue and Fascia, Open Approach', 'Oralle Pinel');
insert into song (song_id, song_name, song_desc, song_artist) values (112, 'Burmese black mountain tortoise', 'Drainage of Left Scapula with Drainage Device, Open Approach', 'Aloise Shimon');
insert into song (song_id, song_name, song_desc, song_artist) values (113, 'Duck, blue', 'Transfuse Nonaut Red Blood Cells in Central Vein, Perc', 'Clemmie Badham');
insert into song (song_id, song_name, song_desc, song_artist) values (114, 'African wild cat', 'Fluoroscopy of Right Clavicle', 'Clementia Beekman');
insert into song (song_id, song_name, song_desc, song_artist) values (115, 'American beaver', 'Revise Contracep Dev in Uterus & Cervix, Perc Endo', 'Tabb Paolone');
insert into song (song_id, song_name, song_desc, song_artist) values (116, 'Echidna, short-beaked', 'Occlusion of Right Fallopian Tube, Perc Endo Approach', 'Catharina Barniss');
insert into song (song_id, song_name, song_desc, song_artist) values (117, 'Mongoose, small indian', 'Drainage of R Tunica Vaginalis, Perc Endo Approach, Diagn', 'Glenn Ambage');
insert into song (song_id, song_name, song_desc, song_artist) values (118, 'Red-necked phalarope', 'Removal of Drain Dev from Trunk Subcu/Fascia, Open Approach', 'Micaela Aldersley');
insert into song (song_id, song_name, song_desc, song_artist) values (119, 'Stork, marabou', 'Alteration of Left Axilla with Nonaut Sub, Perc Approach', 'Midge Gatchell');
insert into song (song_id, song_name, song_desc, song_artist) values (120, 'King cormorant', 'Dilation of L Renal Art with Drug-elut Intra, Open Approach', 'Kendrick Ragbourne');
insert into song (song_id, song_name, song_desc, song_artist) values (121, 'Purple grenadier', 'Reattachment of Left Lung, Open Approach', 'Romola Anshell');
insert into song (song_id, song_name, song_desc, song_artist) values (122, 'Common goldeneye', 'Drainage of Bladder, Open Approach', 'Katalin Nano');
insert into song (song_id, song_name, song_desc, song_artist) values (123, 'Monitor, water', 'Supplement Esophageal Vein with Nonaut Sub, Open Approach', 'Georgette McIlwraith');
insert into song (song_id, song_name, song_desc, song_artist) values (124, 'Australian spiny anteater', 'Removal of Autol Sub from Up Art, Perc Approach', 'Kala Wellstead');
insert into song (song_id, song_name, song_desc, song_artist) values (125, 'Flicker, field', 'Division of Left Trunk Muscle, Open Approach', 'Nicolina Bispo');
insert into song (song_id, song_name, song_desc, song_artist) values (126, 'Indian peacock', 'Fluoroscopy of Larynx using Other Contrast', 'Tarra Blewett');
insert into song (song_id, song_name, song_desc, song_artist) values (127, 'Black-crowned night heron', 'Excision of Face Skin, External Approach, Diagnostic', 'Ingeborg McCurtin');
insert into song (song_id, song_name, song_desc, song_artist) values (128, 'Ring-necked pheasant', 'Transfer Abducens Nerve to Oculomotor N, Perc Endo Approach', 'Kelley Barns');
insert into song (song_id, song_name, song_desc, song_artist) values (129, 'Phascogale, brush-tailed', 'Destruction of Middle Esophagus, Via Opening', 'Marice Lune');
insert into song (song_id, song_name, song_desc, song_artist) values (130, 'Egyptian vulture', 'Reposition Left Finger Phalanx, External Approach', 'Lisha Hans');
insert into song (song_id, song_name, song_desc, song_artist) values (131, 'Black-necked stork', 'Restrict Inf Mesent Vein w Intralum Dev, Perc Endo', 'Charline Adcocks');
insert into song (song_id, song_name, song_desc, song_artist) values (132, 'Barbet, black-collared', 'Repair Thyroid Gland Isthmus, Open Approach', 'Silva Shirer');
insert into song (song_id, song_name, song_desc, song_artist) values (133, 'Monkey, vervet', 'Occlusion of R Int Carotid with Intralum Dev, Open Approach', 'Suellen Gravells');
insert into song (song_id, song_name, song_desc, song_artist) values (134, 'Ostrich', 'Reposition Right Metatarsal-Phalangeal Joint, Open Approach', 'Jacinta Bultitude');
insert into song (song_id, song_name, song_desc, song_artist) values (135, 'Lion, california sea', 'Dilate R Com Carotid, Bifurc, w 4 Drug-elut, Open', 'Wilmar Provis');
insert into song (song_id, song_name, song_desc, song_artist) values (136, 'Sheep, stone', 'Planar Nucl Med Imag Up Extrem Lymph w Oth Radionuclide', 'Mahala McKeller');
insert into song (song_id, song_name, song_desc, song_artist) values (137, 'Beaver, eurasian', 'Occlusion of Thoracic Duct, Percutaneous Approach', 'Isobel Palfreman');
insert into song (song_id, song_name, song_desc, song_artist) values (138, 'Woodchuck', 'Excision of Thoracic Nerve, Open Approach', 'Madelin Gherardelli');
insert into song (song_id, song_name, song_desc, song_artist) values (139, 'Paradoxure', 'Reposition Left Tarsal Joint, Open Approach', 'Mikel Dunbabin');
insert into song (song_id, song_name, song_desc, song_artist) values (140, 'Snowy sheathbill', 'Drainage of Left Hip Muscle, Percutaneous Approach', 'Erskine Streather');
insert into song (song_id, song_name, song_desc, song_artist) values (141, 'Sunbird, lesser double-collared', 'Introduction of Nutritional into Low GI, Perc Approach', 'Bibby Eskrigge');
insert into song (song_id, song_name, song_desc, song_artist) values (142, 'Rat, white-faced tree', 'Destruction of Right Diaphragm, Perc Endo Approach', 'Gwennie Chapelhow');
insert into song (song_id, song_name, song_desc, song_artist) values (143, 'Common wombat', 'Insertion of Neuro Lead into Cranial Nrv, Perc Endo Approach', 'Peirce Borley');
insert into song (song_id, song_name, song_desc, song_artist) values (144, 'Fox, grey', 'Drainage of L Abd Tendon with Drain Dev, Perc Endo Approach', 'Virginia Saurat');
insert into song (song_id, song_name, song_desc, song_artist) values (145, 'Dolphin, striped', 'Measurement of Cardiac Rate, External Approach', 'Skipp Boffin');
insert into song (song_id, song_name, song_desc, song_artist) values (146, 'Large cormorant', 'Excision of Right Carpal Joint, Open Approach', 'Amble Lotze');
insert into song (song_id, song_name, song_desc, song_artist) values (147, 'Seal, common', 'Removal of Radioactive Element from R Lung, Perc Approach', 'Gwenny Greenough');
insert into song (song_id, song_name, song_desc, song_artist) values (148, 'Crane, blue', 'Supplement R Up Leg Subcu/Fascia w Nonaut Sub, Perc', 'Sterne Clinnick');
insert into song (song_id, song_name, song_desc, song_artist) values (149, 'Deer, swamp', 'Remove Autol Sub from L Acromioclav Jt, Perc Endo', 'Grayce Rowcliffe');
insert into song (song_id, song_name, song_desc, song_artist) values (150, 'Dama wallaby', 'Resection of Right Lung, Open Approach', 'Denny Clee');
insert into song (song_id, song_name, song_desc, song_artist) values (151, 'Brazilian tapir', 'Reposition Left Upper Arm Muscle, Perc Endo Approach', 'Rob Simmill');
insert into song (song_id, song_name, song_desc, song_artist) values (152, 'Wallaby, red-necked', 'Drainage of Male Perineum, Percutaneous Endoscopic Approach', 'Aggy Greenhouse');
insert into song (song_id, song_name, song_desc, song_artist) values (153, 'Rhea, gray', 'Inspection of Lower Tendon, External Approach', 'Jozef Camis');
insert into song (song_id, song_name, song_desc, song_artist) values (154, 'Black-fronted bulbul', 'Dilation of Lower Artery with Drug-elut Intra, Perc Approach', 'Pru Rantoul');
insert into song (song_id, song_name, song_desc, song_artist) values (155, 'Kangaroo, red', 'Replacement of L Low Femur with Nonaut Sub, Open Approach', 'Antonella Helbeck');
insert into song (song_id, song_name, song_desc, song_artist) values (156, 'Weaver, lesser masked', 'Destruction of Left Ulna, Percutaneous Endoscopic Approach', 'Giulia Speechly');
insert into song (song_id, song_name, song_desc, song_artist) values (157, 'Wallaby, tammar', 'Removal of Bandage on Left Finger', 'Dian Keppe');
insert into song (song_id, song_name, song_desc, song_artist) values (158, 'Downy woodpecker', 'Occlusion of Left Internal Jugular Vein, Perc Endo Approach', 'Ginger Summerlee');
insert into song (song_id, song_name, song_desc, song_artist) values (159, 'Pied avocet', 'CT Scan Bi Salivary Gland w L Osm Contrast, Unenh, Enhance', 'Alexi Wilshire');
insert into song (song_id, song_name, song_desc, song_artist) values (160, 'Bandicoot, short-nosed', 'Inspection of Vagina and Cul-de-sac, External Approach', 'Donielle Clilverd');
insert into song (song_id, song_name, song_desc, song_artist) values (161, 'Black-tailed prairie dog', 'Repair Neck, Stoma, External Approach', 'Liv Siberry');
insert into song (song_id, song_name, song_desc, song_artist) values (162, 'Steller sea lion', 'Resection of Ileum, Endo', 'Jayne Hache');
insert into song (song_id, song_name, song_desc, song_artist) values (163, 'Impala', 'Bypass L Int Iliac Art to R Int Ilia w Autol Art, Open', 'Caren Aubri');
insert into song (song_id, song_name, song_desc, song_artist) values (164, 'Bat, madagascar fruit', 'Revision of Infusion Device in Upper Back, Perc Approach', 'Reginald Dametti');
insert into song (song_id, song_name, song_desc, song_artist) values (165, 'Bush dog', 'Reposition L Metacarpocarp Jt with Int Fix, Perc Approach', 'Vyky Gibben');
insert into song (song_id, song_name, song_desc, song_artist) values (166, 'Hornbill, red-billed', 'Bypass Left Femoral Artery to Low Ex Art, Open Approach', 'Derrick Duncanson');
insert into song (song_id, song_name, song_desc, song_artist) values (167, 'Colobus, magistrate black', 'Revision of Int Fix in L Pelvic Bone, Perc Approach', 'Cassandry Shyres');
insert into song (song_id, song_name, song_desc, song_artist) values (168, 'Baleen whale', 'Drainage of Right Elbow Joint, Percutaneous Approach, Diagn', 'Pren Upton');
insert into song (song_id, song_name, song_desc, song_artist) values (169, 'Clark''s nutcracker', 'Drainage of Hard Palate with Drainage Device, Open Approach', 'Colver Waddicor');
insert into song (song_id, song_name, song_desc, song_artist) values (170, 'Worm snake (unidentified)', 'Dilate L Int Carotid, Bifurc, w 2 Intralum Dev, Perc', 'Leanor Ferrer');
insert into song (song_id, song_name, song_desc, song_artist) values (171, 'Western patch-nosed snake', 'Bypass R Ventricle to R Pulm Art w Nonaut Sub, Open', 'Eduino Gaymar');
insert into song (song_id, song_name, song_desc, song_artist) values (172, 'Baboon, chacma', 'Bypass R Radial Art to R Low Arm Art w Autol Vn, Open', 'Johannes Sodor');
insert into song (song_id, song_name, song_desc, song_artist) values (173, 'Hawk, red-tailed', 'Plain Radiography of Left Hip using Other Contrast', 'Nial Boag');
insert into song (song_id, song_name, song_desc, song_artist) values (174, 'Ground monitor (unidentified)', 'Removal of Monitor Dev from Low Intest Tract, Via Opening', 'Nestor Trace');
insert into song (song_id, song_name, song_desc, song_artist) values (175, 'Greater roadrunner', 'Revision of Nonaut Sub in L Metatarsal, Extern Approach', 'Imojean Auchinleck');
insert into song (song_id, song_name, song_desc, song_artist) values (176, 'Small Indian mongoose', 'Supplement R Axilla Art with Autol Sub, Perc Approach', 'Betsey Hinder');
insert into song (song_id, song_name, song_desc, song_artist) values (177, 'Waterbuck, defassa', 'Bypass Ileum to Desc Colon w Autol Sub, Perc Endo', 'Skelly Donaho');
insert into song (song_id, song_name, song_desc, song_artist) values (178, 'Eastern indigo snake', 'Bypass Left Ureter to Cutan with Synth Sub, Open Approach', 'Trenna Schulke');
insert into song (song_id, song_name, song_desc, song_artist) values (179, 'Colobus, black and white', 'Grooming/Personal Hygiene Treatment using Prosthesis', 'Craig Rowston');
insert into song (song_id, song_name, song_desc, song_artist) values (180, 'Mountain goat', 'Extirpation of Matter from Bilateral Breast, Via Opening', 'Samantha Pearmain');
insert into song (song_id, song_name, song_desc, song_artist) values (181, 'Nighthawk, common', 'Occlusion of Left Fallopian Tube, Via Opening', 'Eric Scotsbrook');
insert into song (song_id, song_name, song_desc, song_artist) values (182, 'Southern boubou', 'Drainage of R Tympanic Membrane, Perc Endo Approach, Diagn', 'Hildy Merricks');
insert into song (song_id, song_name, song_desc, song_artist) values (183, 'Tortoise, galapagos', 'Extirpation of Matter from Left Breast, Open Approach', 'Kenn Ofield');
insert into song (song_id, song_name, song_desc, song_artist) values (184, 'Dragon, frilled', 'Introduction of Oxazolidinones into POC, Perc Approach', 'Kattie Subhan');
insert into song (song_id, song_name, song_desc, song_artist) values (185, 'Springbok', 'Restrict of R Mid Lobe Bronc with Intralum Dev, Via Opening', 'Marris Hardiman');
insert into song (song_id, song_name, song_desc, song_artist) values (186, 'Dassie', 'Drainage of Right Femoral Region, Perc Endo Approach', 'Prince Grgic');
insert into song (song_id, song_name, song_desc, song_artist) values (187, 'Pelican, eastern white', 'Dilation of Left Radial Artery, Perc Endo Approach', 'Liliane Croce');
insert into song (song_id, song_name, song_desc, song_artist) values (188, 'Asian openbill', 'Extraction of Vertebral Bone Marrow, Open Approach, Diagn', 'Warde Ellingsworth');
insert into song (song_id, song_name, song_desc, song_artist) values (189, 'Phalarope, grey', 'Chiropractic Manipulation Cervical Region, Direct Visceral', 'Jedd Maier');
insert into song (song_id, song_name, song_desc, song_artist) values (190, 'Fowl, helmeted guinea', 'Fragmentation in Accessory Pancreatic Duct, Open Approach', 'Dita Latey');
insert into song (song_id, song_name, song_desc, song_artist) values (191, 'Timber wolf', 'Repair Thoracic Vertebral Disc, Open Approach', 'Garrard Vurley');
insert into song (song_id, song_name, song_desc, song_artist) values (192, 'Cormorant, pied', 'Reposition Left Finger Phalangeal Joint, Perc Approach', 'Antoine Burwood');
insert into song (song_id, song_name, song_desc, song_artist) values (193, 'Lion, african', 'Excision of Right Foot Bursa and Ligament, Perc Approach', 'Zacharias Capon');
insert into song (song_id, song_name, song_desc, song_artist) values (194, 'Cormorant, javanese', 'Destruction of Mult Parathyroid, Perc Endo Approach', 'Gradeigh Aistrop');
insert into song (song_id, song_name, song_desc, song_artist) values (195, 'Ground monitor (unidentified)', 'Revision of Int Fix in Skull, Extern Approach', 'Sullivan Ryal');
insert into song (song_id, song_name, song_desc, song_artist) values (196, 'Crane, sarus', 'Drainage of Common Bile Duct with Drain Dev, Open Approach', 'Ruthy Flipsen');
insert into song (song_id, song_name, song_desc, song_artist) values (197, 'Dark-winged trumpeter', 'Bypass 4+ Cor Art from Cor Art w Autol Vn, Perc Endo', 'Aguste Iffland');
insert into song (song_id, song_name, song_desc, song_artist) values (198, 'Dove, little brown', 'Bypass Abd Aorta to B Renal A w Nonaut Sub, Perc Endo', 'Annabal Tixall');
insert into song (song_id, song_name, song_desc, song_artist) values (199, 'Crested bunting', 'Drainage of R Axilla Art with Drain Dev, Perc Approach', 'Atlanta Litzmann');
insert into song (song_id, song_name, song_desc, song_artist) values (200, 'Duiker, gray', 'Reposition Hepatic Vein, Percutaneous Endoscopic Approach', 'Jobey Pourvoieur');
insert into song (song_id, song_name, song_desc, song_artist) values (201, 'Jungle cat', 'Packing of Left Lower Extremity using Packing Material', 'Johannes Agron');
insert into song (song_id, song_name, song_desc, song_artist) values (202, 'Kingfisher, pied', 'Supplement Right Hip Joint with Nonaut Sub, Open Approach', 'Zaria Geockle');
insert into song (song_id, song_name, song_desc, song_artist) values (203, 'Southern screamer', 'Resection of Clitoris, External Approach', 'Nickola Stanlike');
insert into song (song_id, song_name, song_desc, song_artist) values (204, 'Miner''s cat', 'Drainage of R Pleural Cav with Drain Dev, Open Approach', 'Jennee Glusby');
insert into song (song_id, song_name, song_desc, song_artist) values (205, 'Gazelle, grant''s', 'Drainage of Head and Neck Bursa and Ligament, Open Approach', 'Celestyn Duiged');
insert into song (song_id, song_name, song_desc, song_artist) values (206, 'Beaver, european', 'Fragmentation in Pericardium, Open Approach', 'Svend Yeldham');
insert into song (song_id, song_name, song_desc, song_artist) values (207, 'Raccoon, crab-eating', 'Bypass R Int Iliac Art to B Int Ilia, Perc Endo Approach', 'Hyatt Bairstow');
insert into song (song_id, song_name, song_desc, song_artist) values (208, 'Python (unidentified)', 'Drainage of Right Orbit with Drainage Device, Perc Approach', 'Bary Vardon');
insert into song (song_id, song_name, song_desc, song_artist) values (209, 'Ground monitor (unidentified)', 'Replacement of Left Carpal with Synth Sub, Open Approach', 'Eula Vero');
insert into song (song_id, song_name, song_desc, song_artist) values (210, 'Pie, rufous tree', 'Drainage of Right Face Vein with Drain Dev, Open Approach', 'Beatrix Snelman');
insert into song (song_id, song_name, song_desc, song_artist) values (211, 'Wolf, mexican', 'Introduce Monoclonal Antibody in Central Vein, Open', 'Stearne Chaddock');
insert into song (song_id, song_name, song_desc, song_artist) values (212, 'Egret, cattle', 'Reposition Left Radius, Percutaneous Approach', 'Chantal Dimont');
insert into song (song_id, song_name, song_desc, song_artist) values (213, 'Kafue flats lechwe', 'Revision of Infusion Device in Great Vessel, Extern Approach', 'Belvia Records');
insert into song (song_id, song_name, song_desc, song_artist) values (214, 'North American porcupine', 'Change Splint on Right Lower Leg', 'My Hanscombe');
insert into song (song_id, song_name, song_desc, song_artist) values (215, 'Sarus crane', 'Repair Anus, Percutaneous Approach', 'Salvidor Pinckney');
insert into song (song_id, song_name, song_desc, song_artist) values (216, 'White-fronted capuchin', 'Dilate of Gastric Art with Intralum Dev, Perc Endo Approach', 'Bary Pacheco');
insert into song (song_id, song_name, song_desc, song_artist) values (217, 'Indian star tortoise', 'Revision of Ext Fix in R Tibia, Perc Endo Approach', 'Waldemar Tillman');
insert into song (song_id, song_name, song_desc, song_artist) values (218, 'Wallaby, river', 'Inspection of Nasal Bone, Percutaneous Endoscopic Approach', 'Kaleena Beaston');
insert into song (song_id, song_name, song_desc, song_artist) values (219, 'Whale, long-finned pilot', 'Reposition Left Innominate Vein, Perc Endo Approach', 'Kylie Feehely');
insert into song (song_id, song_name, song_desc, song_artist) values (220, 'Sungazer, yellow-brown', 'Release Right External Auditory Canal, Open Approach', 'Allen Appleton');
insert into song (song_id, song_name, song_desc, song_artist) values (221, 'Masked booby', 'Repair Right Lower Femur, Percutaneous Approach', 'Elinor Crumpe');
insert into song (song_id, song_name, song_desc, song_artist) values (222, 'Bear, sloth', 'Resection of R Up Extrem Bursa/Lig, Perc Endo Approach', 'Donelle Yard');
insert into song (song_id, song_name, song_desc, song_artist) values (223, 'African buffalo', 'Supplement Urethra with Autol Sub, Via Opening', 'Jae Leagas');
insert into song (song_id, song_name, song_desc, song_artist) values (224, 'Crab (unidentified)', 'Beam Radiation of Rib(s) using Photons >10 MeV', 'Roman Rogier');
insert into song (song_id, song_name, song_desc, song_artist) values (225, 'White-faced whistling duck', 'Occlusion Up Esophag w Intralum Dev, Perc Endo', 'Paulette Minthorpe');
insert into song (song_id, song_name, song_desc, song_artist) values (226, 'Albatross, waved', 'Remove Synth Sub from Up Extrem Subcu/Fascia, Open', 'Garnet Simionescu');
insert into song (song_id, song_name, song_desc, song_artist) values (227, 'Coot, red-knobbed', 'Extirpate of Matter from R Sphenoid Bone, Perc Endo Approach', 'Harwilll Talman');
insert into song (song_id, song_name, song_desc, song_artist) values (228, 'Porcupine, crested', 'Revision of Ext Fix in L Hip Jt, Perc Endo Approach', 'Axel Du Pre');
insert into song (song_id, song_name, song_desc, song_artist) values (229, 'Steller''s sea lion', 'Replace L Hip Jt w Metal on Poly, Cement, Open', 'Octavia Huws');
insert into song (song_id, song_name, song_desc, song_artist) values (230, 'Prehensile-tailed porcupine', 'Excision of Left Lower Lobe Bronchus, Via Opening', 'Benson Neubigging');
insert into song (song_id, song_name, song_desc, song_artist) values (231, 'Peccary, collared', 'Drainage of Olfactory Nerve, Perc Endo Approach', 'Sloane Hurne');
insert into song (song_id, song_name, song_desc, song_artist) values (232, 'Striped dolphin', 'Removal of Drain Dev from L Toe Phalanx Jt, Perc Approach', 'Seline Jorger');
insert into song (song_id, song_name, song_desc, song_artist) values (233, 'Savanna baboon', 'Revision of Int Fix in R Sacroiliac Jt, Perc Endo Approach', 'D''arcy Swepstone');
insert into song (song_id, song_name, song_desc, song_artist) values (234, 'Lory, rainbow', 'Transfuse of Autol Globulin into Periph Vein, Perc Approach', 'Elsey Porter');
insert into song (song_id, song_name, song_desc, song_artist) values (235, 'Stork, yellow-billed', 'Beam Radiation of Mandible using Photons 1 - 10 MeV', 'Delila Picford');
insert into song (song_id, song_name, song_desc, song_artist) values (236, 'Agama lizard (unidentified)', 'Repair Right Common Iliac Vein, Perc Endo Approach', 'Weber Bachs');
insert into song (song_id, song_name, song_desc, song_artist) values (237, 'Coot, red-knobbed', 'Drainage of R Diaphragm with Drain Dev, Perc Endo Approach', 'Lydia Pedlingham');
insert into song (song_id, song_name, song_desc, song_artist) values (238, 'Raven, white-necked', 'Alteration of R Axilla with Synth Sub, Perc Endo Approach', 'Kat Ewart');
insert into song (song_id, song_name, song_desc, song_artist) values (239, 'Japanese macaque', 'Dilation of L Verteb Art with 2 Intralum Dev, Open Approach', 'Kizzie Spencer');
insert into song (song_id, song_name, song_desc, song_artist) values (240, 'Capuchin, white-fronted', 'Insertion of Infusion Dev into Fem Perineum, Open Approach', 'Jasmine Chasney');
insert into song (song_id, song_name, song_desc, song_artist) values (241, 'Snowy sheathbill', 'Motor Functn Trmt Integu Low Back/LE w Assist Equip', 'Robert MacTeague');
insert into song (song_id, song_name, song_desc, song_artist) values (242, 'Chuckwalla', 'Remove Radioact Elem from Vagina & Cul-de-sac, Perc Endo', 'Kissie Trunks');
insert into song (song_id, song_name, song_desc, song_artist) values (243, 'Warthog', 'Contact Radiation of Back Skin', 'Sherrie Giblett');
insert into song (song_id, song_name, song_desc, song_artist) values (244, 'Peacock, indian', 'Therapeutic Exercise Treatment of Circ Body', 'Peter Tomala');
insert into song (song_id, song_name, song_desc, song_artist) values (245, 'Viper, egyptian', 'Repair Thorax Lymphatic, Percutaneous Endoscopic Approach', 'Phillida Learned');
insert into song (song_id, song_name, song_desc, song_artist) values (246, 'Green-winged macaw', 'Excision of Facial Nerve, Percutaneous Endoscopic Approach', 'Hersh Wherrett');
insert into song (song_id, song_name, song_desc, song_artist) values (247, 'Turkey vulture', 'Irrigate Skin/Mucous Mem w Irrigat, Perc, Diagn', 'Royce Webberley');
insert into song (song_id, song_name, song_desc, song_artist) values (248, 'Bird, red-billed tropic', 'Destruction of Tongue/Palate/Phar Muscle, Perc Endo Approach', 'Adolpho Springett');
insert into song (song_id, song_name, song_desc, song_artist) values (249, 'Blue-breasted cordon bleu', 'Revision of Synth Sub in R Knee Jt, Femoral, Perc Approach', 'Ellery Inold');
insert into song (song_id, song_name, song_desc, song_artist) values (250, 'Common long-nosed armadillo', 'Repair Mesentery, Open Approach', 'Berty Harpin');
insert into song (song_id, song_name, song_desc, song_artist) values (251, 'Galapagos penguin', 'Supplement Ascending Colon with Nonaut Sub, Open Approach', 'Ky Goody');
insert into song (song_id, song_name, song_desc, song_artist) values (252, 'South American puma', 'Drainage of Low Tooth with Drain Dev, Extern Approach, Sing', 'Sylas Mucci');
insert into song (song_id, song_name, song_desc, song_artist) values (253, 'Partridge, coqui', 'Inspection of Gallbladder, External Approach', 'Maynord Timberlake');
insert into song (song_id, song_name, song_desc, song_artist) values (254, 'Rattlesnake, dusky', 'Release Descending Colon, Endo', 'Farlie Sobey');
insert into song (song_id, song_name, song_desc, song_artist) values (255, 'Monkey, rhesus', 'MRI of L Ankle using Oth Contrast, Unenh, Enhance', 'Cleve Wallworth');
insert into song (song_id, song_name, song_desc, song_artist) values (256, 'Dove, galapagos', 'Reposition Right Fibula with Int Fix, Perc Endo Approach', 'Gearard Studeart');
insert into song (song_id, song_name, song_desc, song_artist) values (257, 'Southern screamer', 'Bypass Abdominal Aorta to R Com Ilia, Perc Endo Approach', 'Rafa Dearnaley');
insert into song (song_id, song_name, song_desc, song_artist) values (258, 'Radiated tortoise', 'Transfer L Low Leg Muscle with Subcu, Perc Endo Approach', 'Natalya O''Grady');
insert into song (song_id, song_name, song_desc, song_artist) values (259, 'Topi', 'Removal of Int Fix from R Up Femur, Perc Endo Approach', 'Dinah Strowther');
insert into song (song_id, song_name, song_desc, song_artist) values (260, 'South American meadowlark (unidentified)', 'Removal of Extraluminal Device from Trachea, Perc Approach', 'Kirk O''Breen');
insert into song (song_id, song_name, song_desc, song_artist) values (261, 'Egyptian goose', 'Replace of R Verteb Art with Autol Sub, Perc Endo Approach', 'Hervey Lindenman');
insert into song (song_id, song_name, song_desc, song_artist) values (262, 'Black curlew', 'Resection of Small Intestine, Via Opening', 'Maggi Rodders');
insert into song (song_id, song_name, song_desc, song_artist) values (263, 'Golden-mantled ground squirrel', 'Measurement of POC, Cardiac Sound, Extern Approach', 'Auberta Hatherell');
insert into song (song_id, song_name, song_desc, song_artist) values (264, 'Lion, southern sea', 'Insertion of Infusion Dev into Abd Wall, Perc Endo Approach', 'Dickie Wickersham');
insert into song (song_id, song_name, song_desc, song_artist) values (265, 'Blue fox', 'Immobilization of Face using Splint', 'Aylmar Van der Velde');
insert into song (song_id, song_name, song_desc, song_artist) values (266, 'Richardson''s ground squirrel', 'Bypass R Com Iliac Art to L Com Ilia w Synth Sub, Open', 'Amalee Mila');
insert into song (song_id, song_name, song_desc, song_artist) values (267, 'Lesser mouse lemur', 'Revision of Nonaut Sub in R Shoulder Jt, Perc Approach', 'Wilow Mein');
insert into song (song_id, song_name, song_desc, song_artist) values (268, 'Egyptian goose', 'Revision of Infusion Device in Pancreat Duct, Perc Approach', 'Everard Terney');
insert into song (song_id, song_name, song_desc, song_artist) values (269, 'Lizard, mexican beaded', 'Bypass Ileum to Rectum with Nonaut Sub, Endo', 'Edithe Revening');
insert into song (song_id, song_name, song_desc, song_artist) values (270, 'Goose, andean', 'Drainage of Right Femoral Artery, Perc Endo Approach', 'Adolpho Coghlan');
insert into song (song_id, song_name, song_desc, song_artist) values (271, 'Raccoon, common', 'Excision of Right Ankle Region, Open Approach, Diagnostic', 'Belinda Waszkiewicz');
insert into song (song_id, song_name, song_desc, song_artist) values (272, 'Four-horned antelope', 'Revision of Infusion Device in Vas Deferens, Extern Approach', 'Bailey Pullan');
insert into song (song_id, song_name, song_desc, song_artist) values (273, 'Heron, gray', 'Extirpation of Matter from R Hip Jt, Perc Endo Approach', 'Elmore Itzig');
insert into song (song_id, song_name, song_desc, song_artist) values (274, 'Eagle, golden', 'Reposition Right Radius, Percutaneous Approach', 'Rosalia Burde');
insert into song (song_id, song_name, song_desc, song_artist) values (275, 'Nelson ground squirrel', 'Replacement of R Humeral Shaft with Synth Sub, Open Approach', 'Elbertina Piggrem');
insert into song (song_id, song_name, song_desc, song_artist) values (276, 'Praying mantis (unidentified)', 'Insertion of Infusion Device into Upper Vein, Open Approach', 'Rowena Gwatkins');
insert into song (song_id, song_name, song_desc, song_artist) values (277, 'Azara''s zorro', 'Excision of Left Lower Femur, Open Approach', 'Howie Bedome');
insert into song (song_id, song_name, song_desc, song_artist) values (278, 'American buffalo', 'Occlusion Inf Mesent Vein w Extralum Dev, Open', 'Enrika McConaghy');
insert into song (song_id, song_name, song_desc, song_artist) values (279, 'Gonolek, burchell''s', 'Extirpation of Matter from L Knee Tendon, Perc Endo Approach', 'Humfried Serginson');
insert into song (song_id, song_name, song_desc, song_artist) values (280, 'Stone sheep', 'Dilate L Ulnar Art, Bifurc, w Drug-elut Intra, Perc Endo', 'Clerkclaude Casaccio');
insert into song (song_id, song_name, song_desc, song_artist) values (281, 'Secretary bird', 'Excision of Head, External Approach', 'Elvyn Gioan');
insert into song (song_id, song_name, song_desc, song_artist) values (282, 'Galapagos hawk', 'Resection of Bilateral Spermatic Cords, Open Approach', 'Marci Scouse');
insert into song (song_id, song_name, song_desc, song_artist) values (283, 'Asian red fox', 'Dilation of R Brach Art with 3 Drug-elut, Open Approach', 'Mead Goggan');
insert into song (song_id, song_name, song_desc, song_artist) values (284, 'Orca', 'Bypass Bi Ureter to Colocutan w Nonaut Sub, Perc Endo', 'Clyde Roskeilly');
insert into song (song_id, song_name, song_desc, song_artist) values (285, 'Rhea, common', 'Dilation of Cecum, Open Approach', 'Amabel Cabane');
insert into song (song_id, song_name, song_desc, song_artist) values (286, 'Sheep, red', 'Plain Radiography of Bi Up Extrem Lymph using H Osm Contrast', 'Tynan Jorat');
insert into song (song_id, song_name, song_desc, song_artist) values (287, 'Waved albatross', 'Dilate Splenic Art, Bifurc, w 2 Drug-elut, Open', 'Garnette Longlands');
insert into song (song_id, song_name, song_desc, song_artist) values (288, 'Cereopsis goose', 'Repair Right Colic Artery, Open Approach', 'Chev Beaument');
insert into song (song_id, song_name, song_desc, song_artist) values (289, 'Bushbuck', 'Extirpate matter from Abd Aorta, Bifurc, Perc Endo', 'Ikey Gurery');
insert into song (song_id, song_name, song_desc, song_artist) values (290, 'Gull, kelp', 'Supplement Right Nipple with Nonaut Sub, Perc Approach', 'Marylee Naris');
insert into song (song_id, song_name, song_desc, song_artist) values (291, 'Tree porcupine', 'Revise Infusion Dev in Epididymis/Sperm Cord, Extern', 'Zane Dobbson');
insert into song (song_id, song_name, song_desc, song_artist) values (292, 'Badger, european', 'Revision of Autol Sub in L Toe Phalanx, Perc Endo Approach', 'Mendie Studeart');
insert into song (song_id, song_name, song_desc, song_artist) values (293, 'Fox, pampa gray', 'Comm/Cognit Skill Treatment of Neuro Body using AV Equipment', 'Guinevere Kleinstein');
insert into song (song_id, song_name, song_desc, song_artist) values (294, 'Bandicoot, long-nosed', 'Reposition R Femur Shaft w Monopln Ext Fix, Perc Endo', 'Shannon MacColl');
insert into song (song_id, song_name, song_desc, song_artist) values (295, 'Pie, rufous tree', 'Hyperthermia of Nose', 'Frannie Fussen');
insert into song (song_id, song_name, song_desc, song_artist) values (296, 'Hummingbird (unidentified)', 'Dilate Intracran Art, Bifurc, w 3 Intralum Dev, Perc', 'Noami Bryde');
insert into song (song_id, song_name, song_desc, song_artist) values (297, 'Seal, northern elephant', 'Revision of Autol Sub in R Metacarpocarp Jt, Perc Approach', 'Tillie Osmint');
insert into song (song_id, song_name, song_desc, song_artist) values (298, 'Eastern box turtle', 'Bypass 2 Cor Art from Thor Art w Synth Sub, Perc Endo', 'Mariann Groll');
insert into song (song_id, song_name, song_desc, song_artist) values (299, 'Tayra', 'Dilation of R Up Lobe Bronc with Intralum Dev, Via Opening', 'Diahann Torns');
insert into song (song_id, song_name, song_desc, song_artist) values (300, 'Magpie, australian', 'Supplement R Ankle with Nonaut Sub, Perc Endo Approach', 'Hirsch Cobbold');
