insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (1, 'Hedgehog, south african', 'Replace of R Brach Art with Nonaut Sub, Perc Endo Approach', 9, 459);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (2, 'Blue racer', 'Replace of R Finger Phalanx with Autol Sub, Perc Approach', 15, 515);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (3, 'Swainson''s francolin', 'Release Right External Ear, External Approach', 12, 243);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (4, 'Greater flamingo', 'Inspection of Bilateral Inguinal Region, Open Approach', 15, 270);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (5, 'Asiatic jackal', 'MRI of Fetal Thorax using Oth Contrast', 7, 506);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (6, 'Cat, miner''s', 'Reposition Ascending Colon, Open Approach', 11, 806);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (7, 'Fringe-eared oryx', 'Fragmentation in Right Hepatic Duct, Endo', 8, 724);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (8, 'Northern phalarope', 'Extirpation of Matter from R Main Bronc, Open Approach', 6, 868);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (9, 'Weaver, sociable', 'HDR Brachytherapy of Ureter using Oth Isotope', 12, 900);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (10, 'Openbill, asian', 'Reposition Right Fibula with Ext Fix, Perc Endo Approach', 9, 300);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (11, 'Plover, three-banded', 'Replacement of Gastric Vein with Autol Sub, Open Approach', 2, 374);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (12, 'Thirteen-lined squirrel', 'Inspection of Up Extrem Subcu/Fascia, Open Approach', 10, 55);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (13, 'Beaver, european', 'Replacement of Lower Gingiva with Synth Sub, Open Approach', 2, 473);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (14, 'Great white pelican', 'Restrict of R Up Lobe Bronc with Intralum Dev, Via Opening', 18, 448);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (15, 'Southern ground hornbill', 'Insertion of Int Fix into R Tibia, Perc Approach', 13, 394);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (16, 'Elegant crested tinamou', 'Supplement Nose with Nonaut Sub, Open Approach', 3, 631);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (17, 'Numbat', 'Extirpation of Matter from Phrenic Nerve, Perc Endo Approach', 9, 288);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (18, 'Cheetah', 'Bypass Upper Esophagus to Cutaneous, Endo', 8, 82);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (19, 'Catfish, blue', 'Replace of L Hand Subcu/Fascia with Autol Sub, Perc Approach', 1, 4);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (20, 'Tailless tenrec', 'Fluoroscopy of Left Hand/Finger Joint using Other Contrast', 18, 81);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (21, 'Glider, squirrel', 'Drainage of Rectum, Open Approach', 20, 228);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (22, 'Red hartebeest', 'Bypass L Kidney Pelvis to Cutan w Nonaut Sub, Open', 17, 614);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (23, 'Guerza', 'Revision of Drainage Device in Pineal Body, Extern Approach', 3, 214);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (24, 'Wapiti, elk,', 'Dilation of L Popl Art with 2 Intralum Dev, Open Approach', 18, 572);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (25, 'White-mantled colobus', 'Fluoroscopy Bi Verteb Art w L Osm Contrast, Laser Intraop', 20, 922);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (26, 'African black crake', 'Feeding/Eating Treatment using Other Equipment', 9, 690);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (27, 'Deer, black-tailed', 'Revise Synth Sub in Head & Neck Subcu/Fascia, Extern', 6, 751);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (28, 'Genoveva', 'Destruction of Left Lower Femur, Percutaneous Approach', 4, 489);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (29, 'Capuchin, brown', 'Ultrasonography of Left Subclavian Vein, Intravascular', 14, 915);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (30, 'Camel, dromedary', 'Release Right External Iliac Vein, Percutaneous Approach', 18, 708);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (31, 'Dik, kirk''s dik', 'Dilate L Ext Iliac Art, Bifurc, w 2 Intralum Dev, Perc Endo', 12, 440);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (32, 'Butterfly, tropical buckeye', 'Occlusion of Gastric Vein, Open Approach', 9, 635);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (33, 'Northern phalarope', 'ROM & Jt Mobility Treatment of Neuro Body using Prosthesis', 16, 690);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (34, 'Heron, grey', 'Lower Arteries, Dilation', 1, 558);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (35, 'Horned puffin', 'Drainage of Cervicothoracic Vertebral Disc, Perc Approach', 20, 784);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (36, 'Bee-eater (unidentified)', 'Plain Radiography of Left Epididymis using H Osm Contrast', 4, 474);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (37, 'Porcupine, african', 'Bypass Jejunum to Rectum with Autol Sub, Endo', 8, 808);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (38, 'Magnificent frigate bird', 'Reposition Right Rib with Int Fix, Perc Endo Approach', 16, 957);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (39, 'Grenadier, common', 'Insertion of Int Fix into T-lum Jt, Open Approach', 19, 937);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (40, 'Sambar', 'Revision of Drainage Device in Occip Jt, Open Approach', 1, 992);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (41, 'Monkey, bleeding heart', 'Supplement Scrotum with Nonaut Sub, Extern Approach', 17, 671);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (42, 'Deer, roe', 'Dilation of L Post Tib Art with 4 Drug-elut, Perc Approach', 20, 959);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (43, 'Nighthawk, common', 'Drainage of Left Brachial Artery, Perc Approach, Diagn', 13, 733);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (44, 'Hedgehog, south african', 'Motor Function Treatment of Neuro Head, Neck using Orthosis', 2, 529);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (45, 'Goose, cereopsis', 'Measurement of Biliary Flow, Percutaneous Approach', 2, 633);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (46, 'Blesbok', 'Occlusion Stomach, Pylrs w Extralum Dev, Perc Endo', 20, 948);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (47, 'Dragon, ornate rock', 'Drainage of Amniotic Fluid, Diagnostic from POC, Via Opening', 13, 425);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (48, 'Porcupine, tree', 'Alteration of R Wrist with Nonaut Sub, Open Approach', 18, 716);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (49, 'Cliffchat, mocking', 'Replacement of Urethra with Nonaut Sub, Endo', 6, 545);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (50, 'Langur, hanuman', 'Replace L Frontal Bone w Nonaut Sub, Perc Endo', 19, 284);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (51, 'Wagtail, african pied', 'Transfuse Allo Rel Bone Marrow in Periph Vein, Open', 9, 292);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (52, 'Royal tern', 'Restrict R Hand Vein w Intralum Dev, Perc Endo', 8, 636);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (53, 'Black-backed magpie', 'Replacement of Nasopharynx with Autol Sub, Open Approach', 19, 787);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (54, 'Cobra (unidentified)', 'Removal of Autol Sub from Mesentery, Open Approach', 10, 205);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (55, 'Fowl, helmeted guinea', 'Excision of Right Thorax Muscle, Open Approach, Diagnostic', 6, 148);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (56, 'Southern right whale', 'Release Right Brachial Vein, Open Approach', 3, 617);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (57, 'White-nosed coatimundi', 'Repair Right Main Bronchus, Percutaneous Endoscopic Approach', 8, 471);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (58, 'Spurfowl, yellow-necked', 'CT Scan of Cerv Spine using L Osm Contrast', 5, 614);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (59, 'Pronghorn', 'Drainage of Right External Ear, Open Approach, Diagnostic', 4, 531);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (60, 'Yellow-bellied marmot', 'CT Scan of L Up Extrem using Oth Contrast', 6, 318);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (61, 'Sifaka, verreaux''s', 'Extirpation of Matter from L Subclav Vein, Open Approach', 19, 173);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (62, 'Cardinal, red-capped', 'Revision of Autol Sub in L Metacarpocarp Jt, Perc Approach', 2, 750);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (63, 'Sally lightfoot crab', 'Supplement Left Clavicle with Autol Sub, Open Approach', 19, 756);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (64, 'Black rhinoceros', 'Revision of Drainage Device in Upper Tendon, Open Approach', 16, 422);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (65, 'Possum, western pygmy', 'Restrict of R Up Lobe Bronc with Intralum Dev, Via Opening', 8, 866);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (66, 'Kelp gull', 'Insertion of Infusion Device into Colic Vein, Open Approach', 2, 905);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (67, 'Frogmouth, tawny', 'Revision of Other Device in L Up Extrem, Extern Approach', 7, 347);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (68, 'Verreaux''s sifaka', 'Replace of R Foot Art with Nonaut Sub, Perc Endo Approach', 12, 927);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (69, 'Elk, Wapiti', 'Replacement of R Acetabulum with Nonaut Sub, Perc Approach', 13, 21);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (70, 'Phalarope, red-necked', 'Fluoroscopy of Right Fallopian Tube', 4, 838);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (71, 'Galapagos mockingbird', 'Dilation of Right Eustachian Tube, Via Opening', 18, 350);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (72, 'Blue wildebeest', 'Ultrasonography of Left Jugular Veins, Intravascular', 6, 42);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (73, 'River wallaby', 'Drainage of Left Carpal Joint with Drain Dev, Open Approach', 20, 944);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (74, 'Heron, grey', 'Restriction of Left Pulmonary Vein, Open Approach', 4, 493);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (75, 'Beisa oryx', 'Extraction of R Hip Bursa/Lig, Perc Endo Approach', 14, 8);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (76, 'Yellow-crowned night heron', 'Repair Left Shoulder Muscle, Percutaneous Approach', 11, 395);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (77, 'White-winged dove', 'Replacement of R Colic Art with Nonaut Sub, Open Approach', 7, 448);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (78, 'North American beaver', 'Drainage of Left Hepatic Duct with Drainage Device, Endo', 11, 573);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (79, 'Common zebra', 'Drainage of Trachea, Endo', 6, 839);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (80, 'Southern sea lion', 'Plaque Radiation of Right Breast', 8, 986);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (81, 'White-winged tern', 'Revision of Nonaut Sub in R Rib, Perc Approach', 3, 930);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (82, 'Cormorant, neotropic', 'Drainage of Brachial Plexus, Perc Endo Approach', 5, 307);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (83, 'Adouri (unidentified)', 'Transfer R Foot Subcu/Fascia, Open Approach', 18, 332);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (84, 'Kookaburra, laughing', 'Drainage of Trachea, Percutaneous Approach', 3, 899);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (85, 'Capuchin, brown', 'Introduction of Oth Diagn Subst into Bil/Panc Tract, Endo', 18, 847);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (86, 'Ring-tailed gecko', 'Revision of Bone Growth Stimulator in Skull, Perc Approach', 11, 850);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (87, 'Hornbill, red-billed', 'Dilation of R Thyroid Art with Intralum Dev, Open Approach', 2, 960);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (88, 'Armadillo, seven-banded', 'Dilation of Abdominal Aorta with 3 Drug-elut, Perc Approach', 20, 771);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (89, 'Porcupine, african', 'Removal of Nonaut Sub from Vagina & Cul-de-sac, Endo', 9, 557);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (90, 'Civet, common palm', 'Drainage of Lumbosacral Disc, Percutaneous Approach, Diagn', 19, 123);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (91, 'Eleven-banded armadillo (unidentified)', 'Excision of Para-aortic Body, Perc Endo Approach, Diagn', 17, 810);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (92, 'Caracal', 'Excision of R Temporomandib Jt, Perc Endo Approach', 6, 770);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (93, 'Rhesus macaque', 'Extirpate matter from L Ext Iliac Art, Bifurc, Perc', 4, 803);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (94, 'Black-crowned night heron', 'Fragmentation in Ampulla of Vater, Endo', 18, 627);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (95, 'Musk ox', 'Occlusion Access Pancr Duct w Intralum Dev, Via Opening', 14, 932);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (96, 'White-throated kingfisher', 'Repair Lumbar Plexus, Percutaneous Endoscopic Approach', 17, 154);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (97, 'Parrot, hawk-headed', 'Removal of Drain Dev from Vagina & Cul-de-sac, Perc Approach', 6, 796);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (98, 'Jackal, indian', 'Replace of R Verteb Art with Synth Sub, Perc Endo Approach', 7, 439);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (99, 'Canada goose', 'Removal of Int Fix from R Fibula, Extern Approach', 13, 104);
insert into collection (collection_id, collection_name, collection_desc, user_id, image_id) values (100, 'Eagle, bald', 'Supplement Inf Vena Cava with Nonaut Sub, Perc Endo Approach', 6, 511);
