insert into review (review_id, review_desc, collection_id, user_id) values (1, 'Repair Left Shoulder Tendon, Percutaneous Approach', 22, 19);
insert into review (review_id, review_desc, collection_id, user_id) values (2, 'Removal of Synthetic Substitute from Urethra, Via Natural or Artificial Opening', 17, 16);
insert into review (review_id, review_desc, collection_id, user_id) values (3, 'Resection of Lower Tooth, Multiple, Open Approach', 94, 16);
insert into review (review_id, review_desc, collection_id, user_id) values (4, 'Intraoperative Radiation Therapy (IORT) of Liver', 96, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (5, 'Extirpation of Matter from Left Kidney Pelvis, Via Natural or Artificial Opening', 69, 11);
insert into review (review_id, review_desc, collection_id, user_id) values (6, 'Occlusion of Right Thyroid Artery with Extraluminal Device, Open Approach', 57, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (7, 'Supplement Pericardium with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach', 15, 13);
insert into review (review_id, review_desc, collection_id, user_id) values (8, 'Revision of Radioactive Element in Vagina and Cul-de-sac, Via Natural or Artificial Opening Endoscopic', 91, 15);
insert into review (review_id, review_desc, collection_id, user_id) values (9, 'Release Descending Colon, Percutaneous Endoscopic Approach', 75, 16);
insert into review (review_id, review_desc, collection_id, user_id) values (10, 'Removal of Synthetic Substitute from Upper Back, Percutaneous Approach', 70, 16);
insert into review (review_id, review_desc, collection_id, user_id) values (11, 'Occlusion of Left Femoral Vein, Percutaneous Endoscopic Approach', 1, 13);
insert into review (review_id, review_desc, collection_id, user_id) values (12, 'Ultrasonography of Right Common Carotid Artery, Intravascular', 46, 13);
insert into review (review_id, review_desc, collection_id, user_id) values (13, 'Resection of Pharynx, Open Approach', 22, 3);
insert into review (review_id, review_desc, collection_id, user_id) values (14, 'Excision of Lumbar Plexus, Percutaneous Approach', 55, 6);
insert into review (review_id, review_desc, collection_id, user_id) values (15, 'Imaging, Gastrointestinal System, Ultrasonography', 48, 5);
insert into review (review_id, review_desc, collection_id, user_id) values (16, 'Reposition Right Abdomen Tendon, Open Approach', 97, 19);
insert into review (review_id, review_desc, collection_id, user_id) values (17, 'Introduction of Other Diagnostic Substance into Joints, Percutaneous Approach', 96, 1);
insert into review (review_id, review_desc, collection_id, user_id) values (18, 'Destruction of Left Ventricle, Open Approach', 48, 14);
insert into review (review_id, review_desc, collection_id, user_id) values (19, 'Supplement of Right Eye with Nonautologous Tissue Substitute, Open Approach', 5, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (20, 'Drainage of Bilateral Carotid Bodies, Percutaneous Endoscopic Approach', 26, 2);
insert into review (review_id, review_desc, collection_id, user_id) values (21, 'Replacement of Left Cephalic Vein with Nonautologous Tissue Substitute, Open Approach', 70, 16);
insert into review (review_id, review_desc, collection_id, user_id) values (22, 'Removal of Synthetic Substitute from Left Breast, Open Approach', 73, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (23, 'Revision of Synthetic Substitute in Skull, Open Approach', 21, 14);
insert into review (review_id, review_desc, collection_id, user_id) values (24, 'Ear, Nose, Sinus, Inspection', 34, 14);
insert into review (review_id, review_desc, collection_id, user_id) values (25, 'Removal of Extraluminal Device from Urethra, Open Approach', 63, 5);
insert into review (review_id, review_desc, collection_id, user_id) values (26, 'Insertion of Infusion Device into Left Foot Vein, Open Approach', 20, 12);
insert into review (review_id, review_desc, collection_id, user_id) values (27, 'Dilation of Face Artery, Bifurcation, with Four or More Drug-eluting Intraluminal Devices, Percutaneous Endoscopic Approach', 17, 4);
insert into review (review_id, review_desc, collection_id, user_id) values (28, 'Revision of Internal Fixation Device in Right Temporomandibular Joint, External Approach', 4, 17);
insert into review (review_id, review_desc, collection_id, user_id) values (29, 'Restriction of Ascending Colon, Via Natural or Artificial Opening Endoscopic', 96, 8);
insert into review (review_id, review_desc, collection_id, user_id) values (30, 'Removal of Synthetic Substitute from Right Breast, Open Approach', 28, 13);
insert into review (review_id, review_desc, collection_id, user_id) values (31, 'Excision of Ileum, Percutaneous Endoscopic Approach', 14, 14);
insert into review (review_id, review_desc, collection_id, user_id) values (32, 'Supplement Facial Nerve with Autologous Tissue Substitute, Percutaneous Approach', 53, 17);
insert into review (review_id, review_desc, collection_id, user_id) values (33, 'Replacement of Ventricular Septum with Autologous Tissue Substitute, Open Approach', 98, 20);
insert into review (review_id, review_desc, collection_id, user_id) values (34, 'Removal of Internal Fixation Device from Left Lower Femur, Percutaneous Approach', 30, 19);
insert into review (review_id, review_desc, collection_id, user_id) values (35, 'Reposition Left Acetabulum, Percutaneous Endoscopic Approach', 77, 5);
insert into review (review_id, review_desc, collection_id, user_id) values (36, 'Removal of Radioactive Element from Right Lung, Via Natural or Artificial Opening', 4, 7);
insert into review (review_id, review_desc, collection_id, user_id) values (37, 'Extirpation of Matter from Right Pelvic Bone, Percutaneous Endoscopic Approach', 28, 1);
insert into review (review_id, review_desc, collection_id, user_id) values (38, 'Resection of Right Hip Bursa and Ligament, Percutaneous Endoscopic Approach', 57, 5);
insert into review (review_id, review_desc, collection_id, user_id) values (39, 'Insertion of Intraluminal Device into Left Posterior Tibial Artery, Open Approach', 35, 17);
insert into review (review_id, review_desc, collection_id, user_id) values (40, 'Destruction of Left Vocal Cord, Percutaneous Approach', 64, 12);
insert into review (review_id, review_desc, collection_id, user_id) values (41, 'Repair Left Seminal Vesicle, Open Approach', 33, 7);
insert into review (review_id, review_desc, collection_id, user_id) values (42, 'Revision of Autologous Tissue Substitute in Cranial Nerve, Percutaneous Endoscopic Approach', 64, 12);
insert into review (review_id, review_desc, collection_id, user_id) values (43, 'Revision of Internal Fixation Device in Cervical Vertebral Joint, Percutaneous Approach', 10, 11);
insert into review (review_id, review_desc, collection_id, user_id) values (44, 'Monitoring of Cardiac Electrical Activity, Percutaneous Approach', 11, 16);
insert into review (review_id, review_desc, collection_id, user_id) values (45, 'Repair Cervical Vertebra, Percutaneous Approach', 27, 20);
insert into review (review_id, review_desc, collection_id, user_id) values (46, 'Bypass Right Axillary Artery to Right Extracranial Artery with Nonautologous Tissue Substitute, Open Approach', 3, 17);
insert into review (review_id, review_desc, collection_id, user_id) values (47, 'Alteration of Left Wrist Region with Synthetic Substitute, Open Approach', 38, 8);
insert into review (review_id, review_desc, collection_id, user_id) values (48, 'Alteration of Face Subcutaneous Tissue and Fascia, Open Approach', 55, 10);
insert into review (review_id, review_desc, collection_id, user_id) values (49, 'Insertion of Airway into Nasopharynx, Via Natural or Artificial Opening', 9, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (50, 'Detachment at Right 4th Toe, High, Open Approach', 36, 13);
insert into review (review_id, review_desc, collection_id, user_id) values (51, 'Replacement of Left Sphenoid Bone with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach', 19, 15);
insert into review (review_id, review_desc, collection_id, user_id) values (52, 'Heart and Great Vessels, Transplantation', 91, 20);
insert into review (review_id, review_desc, collection_id, user_id) values (53, 'Dilation of Right External Jugular Vein, Percutaneous Approach', 40, 16);
insert into review (review_id, review_desc, collection_id, user_id) values (54, 'Fusion of Thoracic Vertebral Joint with Interbody Fusion Device, Posterior Approach, Posterior Column, Open Approach', 53, 20);
insert into review (review_id, review_desc, collection_id, user_id) values (55, 'Drainage of Left Acetabulum, Open Approach', 52, 4);
insert into review (review_id, review_desc, collection_id, user_id) values (56, 'Dilation of Left Common Iliac Artery with Two Intraluminal Devices, Percutaneous Approach', 10, 11);
insert into review (review_id, review_desc, collection_id, user_id) values (57, 'Extirpation of Matter from Right Patella, Percutaneous Endoscopic Approach', 3, 1);
insert into review (review_id, review_desc, collection_id, user_id) values (58, 'Drainage of Left Tarsal Joint with Drainage Device, Open Approach', 34, 15);
insert into review (review_id, review_desc, collection_id, user_id) values (59, 'Dilation of Right Internal Iliac Artery with Two Intraluminal Devices, Percutaneous Endoscopic Approach', 65, 8);
insert into review (review_id, review_desc, collection_id, user_id) values (60, 'Immobilization of Right Upper Leg using Splint', 77, 19);
insert into review (review_id, review_desc, collection_id, user_id) values (61, 'Insertion of Facet Replacement Spinal Stabilization Device into Cervicothoracic Vertebral Joint, Percutaneous Endoscopic Approach', 7, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (62, 'Dilation of Left Main Bronchus with Intraluminal Device, Percutaneous Approach', 58, 11);
insert into review (review_id, review_desc, collection_id, user_id) values (63, 'Release Right Lower Arm and Wrist Muscle, Percutaneous Endoscopic Approach', 27, 8);
insert into review (review_id, review_desc, collection_id, user_id) values (64, 'Auditory Processing Treatment using Computer', 85, 4);
insert into review (review_id, review_desc, collection_id, user_id) values (65, 'Release Right Lower Extremity Lymphatic, Percutaneous Approach', 8, 1);
insert into review (review_id, review_desc, collection_id, user_id) values (66, 'Revision of Intraluminal Device in Pancreas, External Approach', 61, 8);
insert into review (review_id, review_desc, collection_id, user_id) values (67, 'Occlusion of Right Femoral Artery, Percutaneous Approach', 52, 9);
insert into review (review_id, review_desc, collection_id, user_id) values (68, 'Release Toe Nail, External Approach', 4, 8);
insert into review (review_id, review_desc, collection_id, user_id) values (69, 'Drainage of Left Upper Lobe Bronchus with Drainage Device, Open Approach', 60, 19);
insert into review (review_id, review_desc, collection_id, user_id) values (70, 'Revision of Autologous Tissue Substitute in Right Glenoid Cavity, Percutaneous Endoscopic Approach', 58, 17);
insert into review (review_id, review_desc, collection_id, user_id) values (71, 'Excision of Supernumerary Breast, Via Natural or Artificial Opening', 82, 5);
insert into review (review_id, review_desc, collection_id, user_id) values (72, 'Release Right Hepatic Duct, Percutaneous Approach', 94, 7);
insert into review (review_id, review_desc, collection_id, user_id) values (73, 'Bypass Left Internal Jugular Vein to Upper Vein with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach', 15, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (74, 'Irrigation of Respiratory Tract using Irrigating Substance, Percutaneous Approach, Diagnostic', 49, 12);
insert into review (review_id, review_desc, collection_id, user_id) values (75, 'Occlusion of Left Anterior Tibial Artery with Intraluminal Device, Percutaneous Endoscopic Approach', 11, 5);
insert into review (review_id, review_desc, collection_id, user_id) values (76, 'Intraoperative Radiation Therapy (IORT) of Nasopharynx', 75, 9);
insert into review (review_id, review_desc, collection_id, user_id) values (77, 'Insertion of Intraluminal Device into Right Subclavian Vein, Percutaneous Endoscopic Approach', 69, 6);
insert into review (review_id, review_desc, collection_id, user_id) values (78, 'Destruction of Thoracic Spinal Cord, Open Approach', 3, 20);
insert into review (review_id, review_desc, collection_id, user_id) values (79, 'Dilation of Pharynx, Via Natural or Artificial Opening Endoscopic', 2, 11);
insert into review (review_id, review_desc, collection_id, user_id) values (80, 'Restriction of Left Ulnar Artery with Intraluminal Device, Percutaneous Endoscopic Approach', 82, 20);
insert into review (review_id, review_desc, collection_id, user_id) values (81, 'Destruction of Right Metatarsal, Open Approach', 71, 15);
insert into review (review_id, review_desc, collection_id, user_id) values (82, 'Control Bleeding in Face, Open Approach', 42, 12);
insert into review (review_id, review_desc, collection_id, user_id) values (83, 'Inspection of Ureter, Open Approach', 23, 12);
insert into review (review_id, review_desc, collection_id, user_id) values (84, 'Supplement Abdominal Wall with Synthetic Substitute, Open Approach', 46, 16);
insert into review (review_id, review_desc, collection_id, user_id) values (85, 'Insertion of Intraluminal Device into Tracheobronchial Tree, Open Approach', 51, 10);
insert into review (review_id, review_desc, collection_id, user_id) values (86, 'Restriction of Right Common Iliac Vein with Extraluminal Device, Open Approach', 31, 10);
insert into review (review_id, review_desc, collection_id, user_id) values (87, 'Repair Brain, Open Approach', 26, 9);
insert into review (review_id, review_desc, collection_id, user_id) values (88, 'Removal of Infusion Device from Right Metatarsal-Tarsal Joint, Percutaneous Endoscopic Approach', 59, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (89, 'Revision of Drainage Device in Peritoneum, Percutaneous Approach', 32, 14);
insert into review (review_id, review_desc, collection_id, user_id) values (90, 'Restriction of Upper Esophagus with Intraluminal Device, Open Approach', 96, 12);
insert into review (review_id, review_desc, collection_id, user_id) values (91, 'Replacement of Left Radial Artery with Autologous Tissue Substitute, Open Approach', 20, 11);
insert into review (review_id, review_desc, collection_id, user_id) values (92, 'Revision of Synthetic Substitute in Right Ankle Joint, External Approach', 28, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (93, 'Occlusion of Right External Jugular Vein with Extraluminal Device, Percutaneous Approach', 35, 5);
insert into review (review_id, review_desc, collection_id, user_id) values (94, 'Resection of Transverse Colon, Via Natural or Artificial Opening Endoscopic', 37, 19);
insert into review (review_id, review_desc, collection_id, user_id) values (95, 'Release Right External Auditory Canal, Percutaneous Endoscopic Approach', 34, 7);
insert into review (review_id, review_desc, collection_id, user_id) values (96, 'Bypass Left Subclavian Artery to Bilateral Lower Arm Artery with Autologous Venous Tissue, Open Approach', 58, 4);
insert into review (review_id, review_desc, collection_id, user_id) values (97, 'Removal of Internal Fixation Device from Left Clavicle, Percutaneous Approach', 96, 14);
insert into review (review_id, review_desc, collection_id, user_id) values (98, 'Drainage of Retroperitoneum, Open Approach', 55, 3);
insert into review (review_id, review_desc, collection_id, user_id) values (99, 'Inspection of Left Femoral Region, Open Approach', 3, 7);
insert into review (review_id, review_desc, collection_id, user_id) values (100, 'Extirpation of Matter from Jejunum, Percutaneous Approach', 58, 5);
insert into review (review_id, review_desc, collection_id, user_id) values (101, 'Drainage of Right Renal Artery, Open Approach, Diagnostic', 52, 12);
insert into review (review_id, review_desc, collection_id, user_id) values (102, 'Fusion of 2 or more Cervical Vertebral Joints with Nonautologous Tissue Substitute, Anterior Approach, Anterior Column, Percutaneous Approach', 52, 6);
insert into review (review_id, review_desc, collection_id, user_id) values (103, 'Removal of Autologous Tissue Substitute from Right Clavicle, Open Approach', 49, 5);
insert into review (review_id, review_desc, collection_id, user_id) values (104, 'Drainage of Pelvis Lymphatic, Percutaneous Endoscopic Approach', 39, 12);
insert into review (review_id, review_desc, collection_id, user_id) values (105, 'Revision of Internal Fixation Device in Right Finger Phalangeal Joint, Open Approach', 40, 14);
insert into review (review_id, review_desc, collection_id, user_id) values (106, 'Revision of Monitoring Device in Pleura, Percutaneous Endoscopic Approach', 36, 6);
insert into review (review_id, review_desc, collection_id, user_id) values (107, 'Supplement Jejunum with Nonautologous Tissue Substitute, Open Approach', 99, 15);
insert into review (review_id, review_desc, collection_id, user_id) values (108, 'Bypass Right Popliteal Artery to Popliteal Artery with Autologous Venous Tissue, Percutaneous Endoscopic Approach', 49, 10);
insert into review (review_id, review_desc, collection_id, user_id) values (109, 'Plain Radiography of Right Toe(s)', 14, 17);
insert into review (review_id, review_desc, collection_id, user_id) values (110, 'Dilation of Left Subclavian Artery, Bifurcation, with Drug-eluting Intraluminal Device, Open Approach', 66, 5);
insert into review (review_id, review_desc, collection_id, user_id) values (111, 'Replacement of Right Vocal Cord with Nonautologous Tissue Substitute, Via Natural or Artificial Opening Endoscopic', 93, 9);
insert into review (review_id, review_desc, collection_id, user_id) values (112, 'Repair Sigmoid Colon, Via Natural or Artificial Opening', 4, 8);
insert into review (review_id, review_desc, collection_id, user_id) values (113, 'Dilation of Ileocecal Valve with Intraluminal Device, Percutaneous Approach', 57, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (114, 'Beam Radiation of Radius/Ulna using Heavy Particles (Protons,Ions)', 19, 15);
insert into review (review_id, review_desc, collection_id, user_id) values (115, 'Beam Radiation of Gallbladder using Neutron Capture', 10, 10);
insert into review (review_id, review_desc, collection_id, user_id) values (116, 'Bypass Left Ventricle to Pulmonary Trunk with Autologous Venous Tissue, Percutaneous Endoscopic Approach', 37, 9);
insert into review (review_id, review_desc, collection_id, user_id) values (117, 'Resection of Right Hip Bursa and Ligament, Open Approach', 39, 5);
insert into review (review_id, review_desc, collection_id, user_id) values (118, 'Revision of Extraluminal Device in Lymphatic, External Approach', 79, 19);
insert into review (review_id, review_desc, collection_id, user_id) values (119, 'Release Left Face Vein, Percutaneous Approach', 12, 17);
insert into review (review_id, review_desc, collection_id, user_id) values (120, 'Excision of Nasopharynx, Via Natural or Artificial Opening', 86, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (121, 'Bypass Left Axillary Artery to Left Upper Leg Artery with Nonautologous Tissue Substitute, Open Approach', 65, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (122, 'Revision of Synthetic Substitute in Right Breast, Open Approach', 13, 20);
insert into review (review_id, review_desc, collection_id, user_id) values (123, 'Replacement of Uvula with Autologous Tissue Substitute, External Approach', 30, 7);
insert into review (review_id, review_desc, collection_id, user_id) values (124, 'Supplement Left Tarsal with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach', 84, 7);
insert into review (review_id, review_desc, collection_id, user_id) values (125, 'Monaural Hearing Aid Assessment using Assistive Listening Equipment', 63, 12);
insert into review (review_id, review_desc, collection_id, user_id) values (126, 'Drainage of Medulla Oblongata with Drainage Device, Open Approach', 50, 10);
insert into review (review_id, review_desc, collection_id, user_id) values (127, 'Insertion of Infusion Device into Left Tarsal Joint, Percutaneous Approach', 2, 11);
insert into review (review_id, review_desc, collection_id, user_id) values (128, 'Dilation of Intracranial Artery with Four or More Intraluminal Devices, Percutaneous Endoscopic Approach', 15, 16);
insert into review (review_id, review_desc, collection_id, user_id) values (129, 'Extirpation of Matter from Sacral Plexus, Percutaneous Approach', 20, 19);
insert into review (review_id, review_desc, collection_id, user_id) values (130, 'Revision of Synthetic Substitute in Left Hip Joint, Femoral Surface, Open Approach', 54, 8);
insert into review (review_id, review_desc, collection_id, user_id) values (131, 'Fusion of 8 or more Thoracic Vertebral Joints with Interbody Fusion Device, Posterior Approach, Anterior Column, Open Approach', 28, 8);
insert into review (review_id, review_desc, collection_id, user_id) values (132, 'Extirpation of Matter from Cisterna Chyli, Percutaneous Endoscopic Approach', 59, 6);
insert into review (review_id, review_desc, collection_id, user_id) values (133, 'Bypass Abdominal Aorta to Right Femoral Artery, Percutaneous Endoscopic Approach', 97, 3);
insert into review (review_id, review_desc, collection_id, user_id) values (134, 'Articulation/Phonology Treatment using Speech Analysis Equipment', 88, 16);
insert into review (review_id, review_desc, collection_id, user_id) values (135, 'Repair Head Muscle, Percutaneous Approach', 91, 9);
insert into review (review_id, review_desc, collection_id, user_id) values (136, 'Dilation of Left Lacrimal Duct with Intraluminal Device, Via Natural or Artificial Opening', 34, 19);
insert into review (review_id, review_desc, collection_id, user_id) values (137, 'Occlusion of Left Subclavian Vein with Intraluminal Device, Percutaneous Endoscopic Approach', 28, 16);
insert into review (review_id, review_desc, collection_id, user_id) values (138, 'Supplement Right Lacrimal Bone with Synthetic Substitute, Percutaneous Approach', 95, 7);
insert into review (review_id, review_desc, collection_id, user_id) values (139, 'Revision of Internal Fixation Device in Left Clavicle, External Approach', 94, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (140, 'Reposition Brachial Plexus, Percutaneous Endoscopic Approach', 37, 12);
insert into review (review_id, review_desc, collection_id, user_id) values (141, 'Division of Left Temporal Bone, Percutaneous Approach', 5, 4);
insert into review (review_id, review_desc, collection_id, user_id) values (142, 'Drainage of Bilateral Spermatic Cords, Percutaneous Approach', 44, 2);
insert into review (review_id, review_desc, collection_id, user_id) values (143, 'Magnetic Resonance Imaging (MRI) of Left Wrist using Other Contrast, Unenhanced and Enhanced', 58, 3);
insert into review (review_id, review_desc, collection_id, user_id) values (144, 'Destruction of Cecum, Percutaneous Endoscopic Approach', 75, 17);
insert into review (review_id, review_desc, collection_id, user_id) values (145, 'Removal of Drainage Device from Right Tympanic Membrane, External Approach', 43, 1);
insert into review (review_id, review_desc, collection_id, user_id) values (146, 'Physical Rehabilitation and Diagnostic Audiology, Rehabilitation, Caregiver Training', 99, 14);
insert into review (review_id, review_desc, collection_id, user_id) values (147, 'Excision of Left Scapula, Percutaneous Approach, Diagnostic', 97, 5);
insert into review (review_id, review_desc, collection_id, user_id) values (148, 'Supplement Stomach, Pylorus with Nonautologous Tissue Substitute, Via Natural or Artificial Opening', 65, 11);
insert into review (review_id, review_desc, collection_id, user_id) values (149, 'Removal of Synthetic Substitute from Head and Neck Subcutaneous Tissue and Fascia, Percutaneous Approach', 42, 17);
insert into review (review_id, review_desc, collection_id, user_id) values (150, 'Bypass Left Internal Iliac Artery to Foot Artery with Autologous Venous Tissue, Open Approach', 30, 9);
insert into review (review_id, review_desc, collection_id, user_id) values (151, 'Removal of Interbody Fusion Device from Cervical Vertebral Joint, Percutaneous Endoscopic Approach', 19, 2);
insert into review (review_id, review_desc, collection_id, user_id) values (152, 'Revision of Drainage Device in Scrotum and Tunica Vaginalis, Open Approach', 28, 14);
insert into review (review_id, review_desc, collection_id, user_id) values (153, 'Insertion of Infusion Device into Left Lower Extremity, Percutaneous Endoscopic Approach', 100, 4);
insert into review (review_id, review_desc, collection_id, user_id) values (154, 'Destruction of Right Carpal, Percutaneous Endoscopic Approach', 37, 15);
insert into review (review_id, review_desc, collection_id, user_id) values (155, 'Bypass Ascending Colon to Ascending Colon with Autologous Tissue Substitute, Via Natural or Artificial Opening Endoscopic', 28, 3);
insert into review (review_id, review_desc, collection_id, user_id) values (156, 'Neuromotor Development Assessment of Neurological System - Lower Back / Lower Extremity', 5, 8);
insert into review (review_id, review_desc, collection_id, user_id) values (157, 'Dilation of Left Common Carotid Artery with Three Drug-eluting Intraluminal Devices, Open Approach', 45, 1);
insert into review (review_id, review_desc, collection_id, user_id) values (158, 'Removal of Synthetic Substitute from Pelvic Cavity, Percutaneous Endoscopic Approach', 1, 15);
insert into review (review_id, review_desc, collection_id, user_id) values (159, 'Drainage of Left Axillary Vein, Percutaneous Endoscopic Approach, Diagnostic', 17, 11);
insert into review (review_id, review_desc, collection_id, user_id) values (160, 'Motor Function Assessment of Neurological System - Upper Back / Upper Extremity', 50, 20);
insert into review (review_id, review_desc, collection_id, user_id) values (161, 'Reposition Left Tympanic Membrane, Via Natural or Artificial Opening Endoscopic', 22, 10);
insert into review (review_id, review_desc, collection_id, user_id) values (162, 'Drainage of Right Lesser Saphenous Vein with Drainage Device, Percutaneous Endoscopic Approach', 78, 2);
insert into review (review_id, review_desc, collection_id, user_id) values (163, 'Excision of Right Hip Muscle, Percutaneous Approach', 83, 5);
insert into review (review_id, review_desc, collection_id, user_id) values (164, 'Replacement of Bilateral External Ear with Nonautologous Tissue Substitute, External Approach', 84, 9);
insert into review (review_id, review_desc, collection_id, user_id) values (165, 'Resection of Bilateral Fallopian Tubes, Via Natural or Artificial Opening', 54, 9);
insert into review (review_id, review_desc, collection_id, user_id) values (166, 'Removal of Autologous Tissue Substitute from Left Eye, Via Natural or Artificial Opening Endoscopic', 76, 17);
insert into review (review_id, review_desc, collection_id, user_id) values (167, 'Drainage of Left Vas Deferens, Open Approach, Diagnostic', 84, 11);
insert into review (review_id, review_desc, collection_id, user_id) values (168, 'Revision of Nonautologous Tissue Substitute in Right Glenoid Cavity, External Approach', 1, 7);
insert into review (review_id, review_desc, collection_id, user_id) values (169, 'Replacement of Right Face Vein with Synthetic Substitute, Open Approach', 7, 16);
insert into review (review_id, review_desc, collection_id, user_id) values (170, 'Replacement of Left Basilic Vein with Autologous Tissue Substitute, Percutaneous Endoscopic Approach', 71, 16);
insert into review (review_id, review_desc, collection_id, user_id) values (171, 'Removal of Infusion Device from Male Perineum, Percutaneous Endoscopic Approach', 86, 14);
insert into review (review_id, review_desc, collection_id, user_id) values (172, 'Reposition Left Tibia with External Fixation Device, Percutaneous Approach', 9, 20);
insert into review (review_id, review_desc, collection_id, user_id) values (173, 'Dilation of Hepatic Artery, Bifurcation, Percutaneous Approach', 3, 7);
insert into review (review_id, review_desc, collection_id, user_id) values (174, 'Release Right Lower Extremity Lymphatic, Percutaneous Approach', 4, 10);
insert into review (review_id, review_desc, collection_id, user_id) values (175, 'Dilation of Right Temporal Artery, Bifurcation, with Drug-eluting Intraluminal Device, Percutaneous Approach', 91, 4);
insert into review (review_id, review_desc, collection_id, user_id) values (176, 'Dilation of Intracranial Artery, Bifurcation, with Four or More Drug-eluting Intraluminal Devices, Open Approach', 48, 4);
insert into review (review_id, review_desc, collection_id, user_id) values (177, 'Removal of Extraluminal Device from Lymphatic, Percutaneous Endoscopic Approach', 51, 2);
insert into review (review_id, review_desc, collection_id, user_id) values (178, 'Removal of Nonautologous Tissue Substitute from Penis, Via Natural or Artificial Opening', 35, 4);
insert into review (review_id, review_desc, collection_id, user_id) values (179, 'Destruction of Minor Salivary Gland, Percutaneous Approach', 91, 14);
insert into review (review_id, review_desc, collection_id, user_id) values (180, 'Bypass Right Ureter to Left Ureter, Percutaneous Endoscopic Approach', 50, 4);
insert into review (review_id, review_desc, collection_id, user_id) values (181, 'Supplement Left Retinal Vessel with Autologous Tissue Substitute, Percutaneous Approach', 77, 12);
insert into review (review_id, review_desc, collection_id, user_id) values (182, 'Supplement Right Radius with Autologous Tissue Substitute, Percutaneous Approach', 18, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (183, 'Change Intermittent Pressure Device on Right Lower Leg', 13, 16);
insert into review (review_id, review_desc, collection_id, user_id) values (184, 'Removal of Radioactive Element from Prostate and Seminal Vesicles, Via Natural or Artificial Opening Endoscopic', 22, 15);
insert into review (review_id, review_desc, collection_id, user_id) values (185, 'Restriction of Right Foot Artery with Intraluminal Device, Percutaneous Endoscopic Approach', 65, 6);
insert into review (review_id, review_desc, collection_id, user_id) values (186, 'Fluoroscopy of Left Pulmonary Artery using High Osmolar Contrast, Laser Intraoperative', 62, 20);
insert into review (review_id, review_desc, collection_id, user_id) values (187, 'Removal of Infusion Device from Stomach, Via Natural or Artificial Opening Endoscopic', 27, 18);
insert into review (review_id, review_desc, collection_id, user_id) values (188, 'Drainage of Left Fibula, Percutaneous Endoscopic Approach', 5, 7);
insert into review (review_id, review_desc, collection_id, user_id) values (189, 'Excision of Left Buttock, Open Approach', 14, 13);
insert into review (review_id, review_desc, collection_id, user_id) values (190, 'Drainage of Right Palatine Bone, Percutaneous Endoscopic Approach, Diagnostic', 85, 5);
insert into review (review_id, review_desc, collection_id, user_id) values (191, 'Alteration of Right Upper Eyelid, Open Approach', 77, 12);
insert into review (review_id, review_desc, collection_id, user_id) values (192, 'Excision of Nasal Turbinate, Percutaneous Approach', 9, 19);
insert into review (review_id, review_desc, collection_id, user_id) values (193, 'Fusion of Right Sternoclavicular Joint with Synthetic Substitute, Open Approach', 10, 7);
insert into review (review_id, review_desc, collection_id, user_id) values (194, 'Computerized Tomography (CT Scan) of Bilateral Pelvic (Iliac) Veins using Other Contrast', 69, 17);
insert into review (review_id, review_desc, collection_id, user_id) values (195, 'Revision of Infusion Device in Face, External Approach', 11, 1);
insert into review (review_id, review_desc, collection_id, user_id) values (196, 'Low Dose Rate (LDR) Brachytherapy of Mouth using Palladium 103 (Pd-103)', 56, 3);
insert into review (review_id, review_desc, collection_id, user_id) values (197, 'Resection of Right Tunica Vaginalis, Percutaneous Endoscopic Approach', 96, 19);
insert into review (review_id, review_desc, collection_id, user_id) values (198, 'Restriction of Right Renal Vein, Percutaneous Approach', 92, 20);
insert into review (review_id, review_desc, collection_id, user_id) values (199, 'Dilation of Esophagus with Intraluminal Device, Via Natural or Artificial Opening Endoscopic', 95, 17);
insert into review (review_id, review_desc, collection_id, user_id) values (200, 'Excision of Left Vas Deferens, Open Approach', 75, 13);
