insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (1, 'Glossy ibis', 'Bypass R Pulm Art from Subclav w Nonaut Sub, Perc Endo', 689);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (2, 'Fairy penguin', 'Dilate R Peroneal Art, Bifurc, w 3 Intralum Dev, Perc Endo', 345);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (3, 'Dog, bush', 'Alteration of Left Knee Region, Open Approach', 2);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (4, 'Bird, magnificent frigate', 'Bypass R Fallopian Tube to R Fallop w Synth Sub, Open', 895);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (5, 'Dragon, netted rock', 'Supplement Left Axilla with Autol Sub, Perc Endo Approach', 535);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (6, 'Tyrant flycatcher', 'Restriction of Innom Art with Extralum Dev, Perc Approach', 215);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (7, 'North American beaver', 'Occlusion of Lingula Bronc with Intralum Dev, Perc Approach', 496);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (8, 'Woodcock, american', 'Revision of Autol Sub in Nose, Extern Approach', 858);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (9, 'Mudskipper (unidentified)', 'MRI of Low Extrem Tendon using Oth Contrast, Unenh, Enhance', 846);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (10, 'Gull, herring', 'Revision of Nonaut Sub in R Eye, Perc Approach', 640);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (11, 'South African hedgehog', 'CT Scan of R Hip using H Osm Contrast', 753);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (12, 'Red-billed buffalo weaver', 'Revise Synth Sub in L Finger Phalanx Jt, Perc Endo', 818);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (13, 'Whip-tailed wallaby', 'Supplement Left Epididymis with Autol Sub, Open Approach', 185);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (14, 'Dove, ring', 'Bypass Abd Aorta to R Femor A w Autol Vn, Perc Endo', 890);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (15, 'White-fronted bee-eater', 'Insertion of Neuro Lead into Cereb Vent, Perc Approach', 490);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (16, 'Gray langur', 'Remove Drain Dev from R Metatarsotars Jt, Perc Endo', 64);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (17, 'Wallaby, river', 'Reposition Left Maxilla, Open Approach', 642);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (18, 'Kangaroo, eastern grey', 'Introduce of Low dose IL-2 into Central Art, Perc Approach', 258);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (19, 'Glossy starling (unidentified)', 'Dilation of L Ext Iliac Art with 4 Drug-elut, Open Approach', 639);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (20, 'Rhinoceros, square-lipped', 'Resection of Tonsils, External Approach', 359);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (21, 'Grouse, sage', 'Reposition L Shoulder Bursa/Lig, Perc Endo Approach', 879);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (22, 'Cormorant, large', 'Release Left Abdomen Muscle, External Approach', 475);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (23, 'Southern screamer', 'Drainage of Lumsac Disc with Drain Dev, Perc Endo Approach', 407);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (24, 'Gray rhea', 'Excision of Right Upper Lobe Bronchus, Perc Approach, Diagn', 531);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (25, 'Yellow-rumped siskin', 'Replacement of Right Vocal Cord with Autol Sub, Endo', 263);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (26, 'Leadbeateri''s ground hornbill', 'Replace R Low Leg Subcu/Fascia w Nonaut Sub, Open', 39);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (27, 'Fox, silver-backed', 'Dilation of R Brach Art with Intralum Dev, Open Approach', 622);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (28, 'Violet-crested turaco', 'Insert Intralum Dev in R Subclav Vein, Perc Endo', 902);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (29, 'Heron, green-backed', 'Removal of Neuro Lead from L Innom Vein, Extern Approach', 645);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (30, 'Clark''s nutcracker', 'Extirpation of Matter from Lum Disc, Open Approach', 400);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (31, 'Mongoose, yellow', 'Dilate L Verteb Art, Bifurc, w Intralum Dev, Open', 180);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (32, 'Bird, pied butcher', 'Bypass R Cephalic Vein to Up Vein w Autol Art, Open', 748);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (33, 'Duiker, common', 'Destruction of Right Upper Eyelid, Open Approach', 126);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (34, 'Margay', 'Introduction of Other Antineoplastic into Eye, Via Opening', 478);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (35, 'Comb duck', 'Fluoroscopy of L Pulm Vein using H Osm Contrast, Guidance', 315);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (36, 'Tern, white-winged black', 'ROM & Jt Mobility Trmt Musculosk Head, Neck w Oth Equip', 452);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (37, 'Currasow (unidentified)', 'Bypass 1 Cor Art from R Int Mammary w Autol Art, Perc Endo', 206);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (38, 'Pine snake (unidentified)', 'Bypass 2 Cor Art from Aorta w Zooplastic, Perc Endo', 441);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (39, 'Darwin ground finch (unidentified)', 'Insert of Intralum Dev into R Ext Iliac Vein, Open Approach', 665);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (40, 'Wolf, timber', 'Drainage of Right Lower Arm, Percutaneous Approach', 13);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (41, 'Rat, white-faced tree', 'Compression of Right Foot using Pressure Dressing', 131);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (42, 'Vulture, bengal', 'Revision of Monitor Dev in Low Intest Tract, Extern Approach', 405);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (43, 'Squirrel, eastern fox', 'Skin and Breast, Replacement', 732);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (44, 'Squirrel, african bush', 'Excision of L Sup Parathyroid, Open Approach, Diagn', 989);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (45, 'Eastern quoll', 'Supplement Atrial Septum with Zooplastic, Open Approach', 791);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (46, 'American bison', 'Removal of Autol Sub from L Wrist Jt, Perc Endo Approach', 826);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (47, 'Ground monitor (unidentified)', 'Supplement R Knee Jt with Autol Sub, Perc Endo Approach', 300);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (48, 'Brocket, brown', 'Transfuse Nonaut Frozen Red Cells in Central Vein, Open', 198);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (49, 'Southern screamer', 'Insertion of Pacemaker Lead into Pericardium, Open Approach', 770);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (50, 'Galah', 'Drainage of R Thumb Phalanx with Drain Dev, Open Approach', 861);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (51, 'Eagle, long-crested hawk', 'Bypass R Ureter to Colocutan w Nonaut Sub, Perc Endo', 773);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (52, 'Squirrel, eastern fox', 'Extirpation of Matter from Trachea, Open Approach', 849);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (53, 'Hottentot teal', 'Plain Radiography of Right Finger(s)', 224);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (54, 'Long-necked turtle', 'Transfer Acoustic Nerve to Hypogloss Nrv, Perc Endo Approach', 409);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (55, 'Crane, wattled', 'Removal of Infusion Device from R Knee Jt, Perc Approach', 804);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (56, 'Black spider monkey', 'Destruction of Accessory Pancreatic Duct, Endo', 838);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (57, 'Goose, cereopsis', 'Restriction of Right Large Intestine, Endo', 561);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (58, 'Raccoon dog', 'Extraction of Right Trunk Bursa and Ligament, Perc Approach', 345);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (59, 'Scottish highland cow', 'Occlusion of Inferior Vena Cava, Perc Endo Approach', 748);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (60, 'House crow', 'Drainage of L Shoulder Muscle with Drain Dev, Open Approach', 253);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (61, 'Caracal', 'Reposition L Temporomandib Jt with Int Fix, Extern Approach', 269);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (62, 'Dove, laughing', 'Extirpation of Matter from L Acromioclav Jt, Open Approach', 156);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (63, 'Cormorant, little', 'HDR Brachytherapy of Kidney using Californium 252', 854);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (64, 'White spoonbill', 'Replace Scalp Skin w Nonaut Sub, Full Thick, Extern', 344);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (65, 'Red deer', 'CT Scan of R Forearm using Oth Contrast', 141);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (66, 'Colobus, white-mantled', 'Drainage of Lung Lingula, Via Natural or Artificial Opening', 138);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (67, 'Sloth, two-toed', 'Coord/Dexterity Treatment of Integu Body using Prosthesis', 199);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (68, 'Caiman, spectacled', 'Bypass L Popl Art to Foot Art with Autol Vn, Open Approach', 433);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (69, 'Anteater, giant', 'Fluoroscopy of Ileal Diversion Loop', 420);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (70, 'Ring-tailed gecko', 'Replacement of L Hand Art with Autol Sub, Perc Endo Approach', 175);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (71, 'Fairy penguin', 'Insertion of Oth Dev into R Shoulder, Perc Endo Approach', 815);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (72, 'Argalis', 'Revision of Synth Sub in Facial Bone, Open Approach', 90);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (73, 'Spurfowl, yellow-necked', 'Fusion of Right Elbow Joint with Autol Sub, Perc Approach', 500);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (74, 'Bent-toed gecko', 'Insertion of Infusion Dev into R Subclav Art, Perc Approach', 538);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (75, 'Deer, spotted', 'Occlusion of Pelvis Lymph with Intralum Dev, Perc Approach', 370);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (76, 'Corella, long-billed', 'Planar Nucl Med Imag of Skull using Oth Radionuclide', 262);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (77, 'Long-crested hawk eagle', 'Plaque Radiation of Salivary Glands', 971);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (78, 'Trumpeter, green-winged', 'Extirpation of Matter from Upper Esophagus, Via Opening', 397);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (79, 'Chacma baboon', 'Removal of Intraluminal Device from Left Eye, Via Opening', 132);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (80, 'Mexican wolf', 'Transfer Vagus Nerve to Vagus Nerve, Perc Endo Approach', 374);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (81, 'Snow goose', 'CT Scan of Port/Splanch Vein using L Osm Contrast', 388);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (82, 'Jaguarundi', 'Bypass R Foot Vein to Low Vein w Synth Sub, Perc Endo', 6);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (83, 'Eland, common', 'Excision of Right Hip Muscle, Open Approach', 559);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (84, 'Legaan, ground', 'Removal of Neuro Lead from Spinal Canal, Perc Approach', 204);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (85, 'Magnificent frigate bird', 'Excision of Left Kidney Pelvis, Via Opening, Diagn', 492);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (86, 'Nyala', 'Traction of Right Upper Leg using Traction Apparatus', 590);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (87, 'Pied cormorant', 'Repair Sacral Plexus, Percutaneous Endoscopic Approach', 268);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (88, 'Lion, steller sea', 'Resection of Left Ethmoid Sinus, Perc Endo Approach', 887);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (89, 'Bettong, brush-tailed', 'Supplement R Clavicle with Nonaut Sub, Perc Endo Approach', 695);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (90, 'Pelican, great white', 'Revision of Synthetic Substitute in Sternum, Open Approach', 931);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (91, 'Bear, grizzly', 'Removal of Infusion Device from L Elbow Jt, Open Approach', 437);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (92, 'Hartebeest, red', 'Removal of Brace on Right Lower Arm', 343);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (93, 'Pied kingfisher', 'Insertion of Intralum Dev into R Pulm Art, Open Approach', 317);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (94, 'Campo flicker', 'Repair Left Frontal Sinus, Percutaneous Approach', 654);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (95, 'Loris, slender', 'Reattachment of Ileum, Percutaneous Endoscopic Approach', 536);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (96, 'Spotted deer', 'Restrict L Subclav Art w Extralum Dev, Perc Endo', 331);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (97, 'Bird, magnificent frigate', 'Fusion Cerv Jt w Synth Sub, Post Appr A Col, Perc Endo', 921);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (98, 'Dassie', 'Excision of Left Carpal Joint, Percutaneous Approach', 446);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (99, 'Monster, gila', 'Supplement Head with Autol Sub, Open Approach', 39);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (100, 'Nubian bee-eater', 'Dilation of Right Hepatic Duct, Open Approach', 625);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (101, 'Anteater, giant', 'Destruction of Gastric Vein, Perc Endo Approach', 157);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (102, 'Suricate', 'Dilation of Left Renal Artery, Perc Endo Approach', 445);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (103, 'Ground legaan', 'Revise of Infusion Dev in L Metatarsotars Jt, Open Approach', 499);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (104, 'Flamingo, lesser', 'Revision of Autol Sub in R Eye, Open Approach', 552);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (105, 'Greater kudu', 'Bypass R Ureter to Colon with Autol Sub, Perc Endo Approach', 336);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (106, 'Gray heron', 'Destruction of Right Eye, External Approach', 185);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (107, 'Crane, wattled', 'Change Other Device in Penis, External Approach', 502);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (108, 'Four-spotted skimmer', 'CT Scan of L Knee using H Osm Contrast', 694);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (109, 'Reindeer', 'Replacement of Right Face Vein with Autol Sub, Open Approach', 202);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (110, 'Two-toed sloth', 'Dilate L Int Iliac Art, Bifurc, w 2 Drug-elut, Perc Endo', 397);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (111, 'Meerkat, red', 'Removal of Synth Sub from R Low Extrem, Perc Endo Approach', 958);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (112, 'Elephant, african', 'Bypass L Popl Art to Foot Art w Nonaut Sub, Perc Endo', 194);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (113, 'White stork', 'Supplement Duodenum with Nonaut Sub, Perc Endo Approach', 999);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (114, 'African polecat', 'Restriction of Right Lesser Saphenous Vein, Perc Approach', 785);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (115, 'Tarantula, salmon pink bird eater', 'Revision of Synth Sub in R Finger Phalanx, Extern Approach', 754);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (116, 'Argalis', 'Reposition Facial Nerve, Percutaneous Endoscopic Approach', 625);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (117, 'Screamer, crested', 'Revision of Autol Sub in C-thor Jt, Perc Endo Approach', 381);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (118, 'White-bellied sea eagle', 'Repair Mouth and Throat in POC with Oth Dev, Open Approach', 513);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (119, 'Owl, australian masked', 'Bypass L Atrium to R Pulm Vn w Autol Art, Perc Endo', 893);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (120, 'Spurfowl, yellow-necked', 'Fusion of T-lum Jt, Ant Appr A Col, Perc Endo Approach', 561);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (121, 'Magellanic penguin', 'Drainage of Left Shoulder Joint, Percutaneous Approach', 28);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (122, 'Swan, black', 'Excision of Right Upper Leg Tendon, Open Approach', 544);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (123, 'Ring-tailed gecko', 'Excision of Cervical Vertebra, Percutaneous Approach', 838);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (124, 'Burchell''s gonolek', 'Release Hypothalamus, Percutaneous Endoscopic Approach', 590);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (125, 'Pelican, australian', 'Bypass R Kidney Pelvis to R Ureter w Synth Sub, Perc Endo', 329);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (126, 'Cat, african wild', 'Drainage of Right Brachial Vein, Perc Endo Approach', 7);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (127, 'Rat, arboral spiny', 'Supplement Left Middle Ear with Nonaut Sub, Open Approach', 472);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (128, 'Pintail, white-cheeked', 'MRI of R Low Leg using Oth Contrast, Unenh, Enhance', 249);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (129, 'Macaw, scarlet', 'Excision of Left Rib, Percutaneous Endoscopic Approach', 117);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (130, 'American Virginia opossum', 'Destruction of Right Internal Mammary Artery, Open Approach', 577);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (131, 'Sable antelope', 'Drainage of R Extraoc Muscle with Drain Dev, Open Approach', 245);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (132, 'Common pheasant', 'Insertion of Other Device into R Low Extrem, Open Approach', 220);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (133, 'Squirrel, thirteen-lined', 'Repair Right Acromioclavicular Joint, Percutaneous Approach', 863);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (134, 'Rhinoceros, square-lipped', 'Reattachment of Left Main Bronchus, Open Approach', 87);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (135, 'European badger', 'Removal of Other Device from Neck, Perc Endo Approach', 371);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (136, 'Camel, dromedary', 'Occlusion of R Fallopian Tube with Intralum Dev, Via Opening', 984);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (137, 'House crow', 'Lower Arteries, Destruction', 61);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (138, 'Roan antelope', 'Revision of Infusion Device in Cerv Disc, Open Approach', 872);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (139, 'South American puma', 'Excision of Ileum, Open Approach', 481);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (140, 'Squirrel, indian giant', 'Excision of Right Trunk Muscle, Open Approach, Diagnostic', 886);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (141, 'Deer, roe', 'Drainage of Upper Gingiva with Drain Dev, Extern Approach', 782);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (142, 'Black spider monkey', 'Transfer Left Trunk Muscle with Subcu, Open Approach', 79);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (143, 'Snowy owl', 'Revision of Autol Sub in Mouth/Throat, Open Approach', 940);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (144, 'Mongoose, eastern dwarf', 'Drainage of Cervicothoracic Vertebral Disc, Perc Approach', 191);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (145, 'Turtle, long-necked', 'Supplement Atrial Septum with Zooplastic, Perc Endo Approach', 894);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (146, 'Small-toothed palm civet', 'Dilation of R Mid Lobe Bronc with Intralum Dev, Via Opening', 63);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (147, 'Glider, feathertail', 'Bypass L Kidney Pelvis to Ileocutan w Nonaut Sub, Perc Endo', 28);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (148, 'Genoveva', 'Restriction of Carina with Extralum Dev, Perc Approach', 520);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (149, 'African buffalo', 'Imaging, GI Sys, CT Scan', 41);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (150, 'Common wolf', 'Bypass 1 Cor Art from Cor Art with Autol Vn, Open Approach', 331);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (151, 'Legaan, ground', 'Dilation of Left Peroneal Artery, Open Approach', 881);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (152, 'Tortoise, desert', 'Fusion of R Ankle Jt with Autol Sub, Perc Endo Approach', 284);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (153, 'Sarus crane', 'Fluoroscopy of Spinal Art using Oth Contrast, Laser Intraop', 860);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (154, 'Otter, african clawless', 'Revision of Synthetic Substitute in Up Vein, Extern Approach', 720);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (155, 'Siskin, pine', 'Occlusion of R Radial Art with Extralum Dev, Perc Approach', 579);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (156, 'Black spider monkey', 'Restrict of R Subclav Vein with Extralum Dev, Open Approach', 175);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (157, 'Bird, magnificent frigate', 'Dilation of Right Ureter with Intralum Dev, Via Opening', 319);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (158, 'Glider, feathertail', 'Occlusion of Left Ulnar Artery, Perc Endo Approach', 829);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (159, 'Spotted-tailed quoll', 'Bypass R Atrium to L Pulm Art w Autol Art, Perc Endo', 669);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (160, 'Cape wild cat', 'Removal of Monitoring Device from Urethra, External Approach', 444);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (161, 'African pied wagtail', 'Drainage of Bilateral Breast with Drain Dev, Perc Approach', 812);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (162, 'Burmese black mountain tortoise', 'Supplement R Knee Bursa/Lig with Nonaut Sub, Open Approach', 125);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (163, 'African elephant', 'Drain of L Humeral Shaft with Drain Dev, Perc Endo Approach', 881);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (164, 'Skua, great', 'Removal of Intraluminal Device from Bladder, Via Opening', 789);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (165, 'Bontebok', 'Insertion of Bone Stim into Up Bone, Open Approach', 16);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (166, 'Armadillo, seven-banded', 'Revision of Synthetic Substitute in L Hip Jt, Open Approach', 468);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (167, 'Great white pelican', 'Revision of Radioactive Element in Head, Perc Endo Approach', 983);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (168, 'Sugar glider', 'Reposition Right Knee Joint with Ext Fix, Extern Approach', 579);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (169, 'Spotted hyena', 'Beam Radiation of Left Breast using Photons <1 MeV', 895);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (170, 'Snake-necked turtle', 'Robotic Assisted Procedure of Trunk, Perc Endo Approach', 392);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (171, 'Ring-tailed lemur', 'Removal of Infusion Dev from L Elbow Jt, Perc Endo Approach', 867);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (172, 'Salmon pink bird eater tarantula', 'Replacement of L Atrium with Zooplastic, Perc Endo Approach', 82);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (173, 'Chimpanzee', 'Occlusion R Brach Art w Intralum Dev, Perc Endo', 829);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (174, 'Stork, european', 'Revision of Neuro Lead in Periph Nrv, Open Approach', 532);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (175, 'Boa, cook''s tree', 'Revision of Drainage Device in Stomach, Endo', 835);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (176, 'Southern hairy-nosed wombat', 'Exercise Trmt Musculosk Low Back/LE w Electrotherap Equip', 321);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (177, 'Hottentot teal', 'Drainage of Lower Back, Open Approach', 725);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (178, 'Cat, civet', 'Drainage of Left Lesser Saphenous Vein, Open Approach, Diagn', 75);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (179, 'Hornbill, southern ground', 'CT Scan of Spinal Cord using L Osm Contrast', 605);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (180, 'Stanley crane', 'Removal of Drain Dev from Pelvic Cav, Perc Endo Approach', 868);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (181, 'Skua, long-tailed', 'Release Pons, Percutaneous Approach', 760);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (182, 'Little blue penguin', 'Excision of Left Foot Artery, Perc Endo Approach, Diagn', 806);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (183, 'Tarantula', 'Therapeutic Exercise Treatment of Resp Low Back/LE', 529);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (184, 'Eagle, bateleur', 'Monitoring of Venous Pulse, Portal, Percutaneous Approach', 775);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (185, 'Macaw, red and blue', 'Occlusion of Ileum, Percutaneous Approach', 615);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (186, 'Eastern boa constrictor', 'Division of Ulnar Nerve, Open Approach', 152);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (187, 'Ox, musk', 'Extirpation of Matter from Left Vas Deferens, Perc Approach', 657);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (188, 'White-cheeked pintail', 'Oscillating Tracking Assess w Vestib/Balance Equip', 157);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (189, 'Tortoise, asian foreset', 'Revision of Nonaut Sub in R Hip Jt, Extern Approach', 337);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (190, 'Rhea, greater', 'Revision of Infusion Device in Pelvic Cav, Extern Approach', 903);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (191, 'Otter, north american river', 'Detachment at Right Thumb, High, Open Approach', 126);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (192, 'Flamingo, greater', 'Drainage of L Inf Parathyroid, Perc Approach, Diagn', 363);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (193, 'Long-tailed spotted cat', 'LDR Brachytherapy of Adrenal Glands using Cesium 137', 953);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (194, 'Blue-footed booby', 'Bypass Innom Art to L Low Leg Art w Synth Sub, Open', 805);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (195, 'Hudsonian godwit', 'Extraction of Scalp Subcu/Fascia, Open Approach', 395);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (196, 'Red-headed woodpecker', 'Upper Veins, Supplement', 348);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (197, 'Bird, bare-faced go away', 'Insertion of Stimulator Lead into Ureter, Open Approach', 770);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (198, 'Flightless cormorant', 'Insertion of VAD into L Low Leg Subcu/Fascia, Open Approach', 122);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (199, 'Baboon, olive', 'Revision of Autol Sub in Low Art, Extern Approach', 956);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (200, 'Agile wallaby', 'Meds Mgmt for Substance Abuse Treatment, Naloxone', 697);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (201, 'Sarus crane', 'Replacement of Lower Gingiva with Nonaut Sub, Open Approach', 101);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (202, 'North American beaver', 'Excision of Left Carotid Body, Open Approach', 124);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (203, 'Black-throated cardinal', 'Excision of Left Vertebral Artery, Perc Approach, Diagn', 681);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (204, 'Armadillo, common long-nosed', 'Restrict L Innom Vein w Extralum Dev, Perc Endo', 703);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (205, 'Booby, blue-footed', 'Computerized Tomography (CT Scan) of L Tracheobronc Tree', 450);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (206, 'Cape wild cat', 'Extirpation of Matter from Right Lung, Perc Endo Approach', 73);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (207, 'Francolin, coqui', 'Insert Radioact Elem in Oral Cav & Throat, Perc Endo', 988);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (208, 'Northern elephant seal', 'Insertion of Intralum Dev into Hepatobil Duct, Via Opening', 769);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (209, 'Miner''s cat', 'Removal of Radioact Elem from Chest Wall, Perc Approach', 669);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (210, 'Common wolf', 'Excision of Right Hip Muscle, Open Approach, Diagnostic', 686);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (211, 'Desert kangaroo rat', 'Extirpation of Matter from L Lg Intest, Perc Approach', 391);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (212, 'Arboral spiny rat', 'Bypass 4+ Cor Art from L Int Mammary w Nonaut Sub, Open', 679);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (213, 'Porcupine, indian', 'Extirpation of Matter from Left Atrium, Perc Approach', 278);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (214, 'Bird, pied butcher', 'Insert Intralum Dev in R Int Mamm Art, Perc Endo', 231);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (215, 'Deer, roe', 'Excision of Right Hand, Percutaneous Endoscopic Approach', 436);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (216, 'Red-shouldered glossy starling', 'Excision of Right Hand, Open Approach, Diagnostic', 720);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (217, 'Crane, wattled', 'Bypass R Axilla Art to R Up Arm Art w Autol Vn, Open', 302);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (218, 'African skink', 'Inspection of Right Axilla, Percutaneous Approach', 593);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (219, 'Grey mouse lemur', 'Excision of Right Epididymis, Percutaneous Approach, Diagn', 392);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (220, 'Eurasian badger', 'Repair Right Hip Bursa and Ligament, Open Approach', 395);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (221, 'Southern white-crowned shrike', 'HDR Brachytherapy of Diaphragm using Cesium 137', 380);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (222, 'North American beaver', 'Dressing of Left Foot using Bandage', 687);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (223, 'Mourning collared dove', 'Excision of Left Finger Phalangeal Joint, Perc Endo Approach', 381);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (224, 'American marten', 'Removal of Synthetic Substitute from Left Rib, Perc Approach', 673);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (225, 'Pied butcher bird', 'Drainage of Tongue with Drainage Device, Perc Approach', 182);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (226, 'Swan, trumpeter', 'Excision of Right Inferior Parathyroid Gland, Open Approach', 100);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (227, 'Arctic lemming', 'Release Right Ulnar Artery, Percutaneous Endoscopic Approach', 357);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (228, 'Western pygmy possum', 'Bypass L Great Saphenous to Low Vein, Perc Endo Approach', 973);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (229, 'Red-billed buffalo weaver', 'Intraoperative Radiation Therapy (IORT) of Bladder', 514);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (230, 'Baleen whale', 'Replacement of Right Clavicle with Synth Sub, Open Approach', 234);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (231, 'Brush-tailed rat kangaroo', 'Bypass R Femor Vein to Low Vein w Autol Sub, Open', 406);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (232, 'Common mynah', 'Excision of Left Pelvic Bone, Percutaneous Approach, Diagn', 622);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (233, 'Coyote', 'Drainage of Right Upper Arm, Perc Endo Approach, Diagn', 189);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (234, 'Thrasher, curve-billed', 'Restrict Mesenteric Lymph w Extralum Dev, Open', 872);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (235, 'Seal, harbor', 'Release Left Large Intestine, Open Approach', 572);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (236, 'Rainbow lory', 'CT Scan of Bi Com Carotid using Oth Contrast', 816);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (237, 'Flamingo, chilean', 'Extirpation of Matter from 2 Cor Art, Bifurc, Open Approach', 597);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (238, 'Red-breasted nuthatch', 'Excision of Left Tibia, Open Approach', 142);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (239, 'Whale, baleen', 'Occlusion of Duodenum with Intraluminal Device, Via Opening', 82);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (240, 'Ferret, black-footed', 'Excision of Skull, Percutaneous Endoscopic Approach, Diagn', 821);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (241, 'Armadillo, seven-banded', 'Supplement L Neck Muscle with Autol Sub, Perc Endo Approach', 259);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (242, 'Baboon, olive', 'Insertion of Infusion Device into L Fem Art, Perc Approach', 205);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (243, 'Magistrate black colobus', 'Reposition Lum Jt with Int Fix, Perc Approach', 81);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (244, 'Penguin, magellanic', 'Insert of Infusion Dev into Retroperitoneum, Perc Approach', 677);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (245, 'Siskin, yellow-rumped', 'Insert Endobronch Valve in Lingula Bronc, Perc Endo', 689);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (246, 'Groundhog', 'Bypass L Ext Iliac Art to B Ext Ilia w Autol Vn, Perc Endo', 836);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (247, 'Agile wallaby', 'Dilate R Ext Carotid, Bifurc, w 3 Drug-elut, Open', 3);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (248, 'Cockatoo, roseate', 'Release Right Occipital Bone, Percutaneous Approach', 318);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (249, 'Springbok', 'Inspection of Mouth and Throat, Perc Endo Approach', 583);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (250, 'White-cheeked pintail', 'Bypass R Subclav Art to L Up Arm Art w Nonaut Sub, Open', 755);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (251, 'Macaque, japanese', 'Introduce Platelet Inhibitor in Central Vein, Perc', 806);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (252, 'Reedbuck, bohor', 'Removal of Autol Sub from L Eye, Perc Approach', 168);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (253, 'Southern black-backed gull', 'Drainage of Right Pleural Cavity, Perc Approach, Diagn', 789);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (254, 'Ocelot', 'Drainage of R Low Arm Subcu/Fascia, Open Approach', 864);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (255, 'Kangaroo, jungle', 'Reposition Left Tarsal Joint, Open Approach', 774);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (256, 'Yellow-brown sungazer', 'Supplement Right Basilic Vein with Synth Sub, Open Approach', 858);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (257, 'White stork', 'Dilation of Right Vertebral Artery, Open Approach', 242);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (258, 'Whale, long-finned pilot', 'Drainage of Left Vas Deferens with Drain Dev, Perc Approach', 587);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (259, 'Saddle-billed stork', 'Occlusion of Cisterna Chyli with Intralum Dev, Open Approach', 730);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (260, 'Savannah deer (unidentified)', 'Extirpation of Matter from Left Ulna, Open Approach', 790);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (261, 'Sandgrouse, yellow-throated', 'Replace Perineum Subcu/Fascia w Autol Sub, Perc', 52);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (262, 'Bontebok', 'MRI of R Testicle using Oth Contrast', 629);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (263, 'Tiger', 'Bypass L Axilla Art to Low Arm Vein w Autol Art, Open', 621);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (264, 'Indian leopard', 'Excision of Bilateral Lungs, Perc Endo Approach', 340);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (265, 'Horned rattlesnake', 'Release Right Abdomen Tendon, Open Approach', 510);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (266, 'Leadbeateri''s ground hornbill', 'Occlusion of Left Peroneal Artery, Percutaneous Approach', 871);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (267, 'Cat, toddy', 'Revision of Int Fix in Cervcal Vertebra, Perc Endo Approach', 397);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (268, 'Common dolphin', 'Beam Radiation of Pancreas using Neutrons', 70);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (269, 'Crane, blue', 'Drainage of Nose with Drainage Device, Perc Endo Approach', 276);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (270, 'Black-throated cardinal', 'Fusion 2-7 T Jt w Nonaut Sub, Post Appr P Col, Perc Endo', 914);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (271, 'Dove, little brown', 'Drainage of Bone Marrow with Drainage Device, Open Approach', 465);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (272, 'Eurasian beaver', 'Dilation of L Verteb Art with Drug-elut Intra, Perc Approach', 310);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (273, 'Lory, rainbow', 'Bypass Cystic Duct to R Hep Duc w Intralum Dev, Perc Endo', 216);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (274, 'Pine siskin', 'Dilation of Left Foot Artery, Percutaneous Approach', 670);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (275, 'Seal, southern elephant', 'Division of Right Parietal Bone, Open Approach', 718);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (276, 'Deer, white-tailed', 'Revision of Nonaut Sub in R Rib, Perc Endo Approach', 55);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (277, 'Paddy heron (unidentified)', 'Dilation of 1 Cor Art with Intralum Dev, Perc Endo Approach', 9);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (278, 'Burchell''s gonolek', 'Drainage of Middle Esophagus, Via Opening', 515);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (279, 'Madagascar fruit bat', 'Occlusion L Foot Art w Intralum Dev, Perc Endo', 951);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (280, 'Woodpecker, downy', 'Replacement of Hepatic Artery with Synth Sub, Open Approach', 871);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (281, 'Rattlesnake, horned', 'Remove of Synth Sub from R Humeral Shaft, Perc Endo Approach', 180);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (282, 'Little brown bat', 'Restriction of Right Inguinal Lymphatic, Open Approach', 816);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (283, 'Wattled crane', 'Replacement of Right Atrium with Nonaut Sub, Open Approach', 431);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (284, 'Tsessebe', 'Release Left Temporal Artery, Open Approach', 782);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (285, 'Burrowing owl', 'Excision of Left External Auditory Canal, Via Opening', 973);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (286, 'Black-tailed tree creeper', 'Dilation of Left Pulmonary Artery, Open Approach', 438);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (287, 'Desert tortoise', 'Replace of Mitral Valve with Nonaut Sub, Perc Endo Approach', 534);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (288, 'Weaver, chestnut', 'Replace of Papillary Muscle with Autol Sub, Open Approach', 440);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (289, 'Weaver, red-billed buffalo', 'Reposition L Humeral Shaft with Ring Ext Fix, Open Approach', 550);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (290, 'Snowy egret', 'Extirpation of Matter from Right Ureter, Via Opening', 748);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (291, 'Timber wolf', 'HDR Brachytherapy of Tongue using Iodine 125', 618);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (292, 'Cormorant (unidentified)', 'Restrict Pelvis Lymph w Intralum Dev, Perc Endo', 402);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (293, 'White-tailed jackrabbit', 'Removal of Other Device from Head, Perc Endo Approach', 680);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (294, 'Groundhog', 'Insertion of Intramed Fix into L Fibula, Perc Endo Approach', 763);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (295, 'Common duiker', 'Replacement of Pulm Trunk with Zooplastic, Open Approach', 89);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (296, 'Dabchick', 'Restriction of Right Anterior Tibial Artery, Open Approach', 340);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (297, 'Sockeye salmon', 'Bypass R Face Vein to Up Vein with Autol Sub, Open Approach', 306);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (298, 'Capuchin, brown', 'Extirpate matter from L Finger Phalanx Jt, Perc Endo', 776);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (299, 'Uinta ground squirrel', 'Insertion of Stimulator Lead into Bladder, Via Opening', 656);
insert into vinyl (vinyl_id, vinyl_name, vinyl_desc, image_id) values (300, 'Capuchin, black-capped', 'Bypass Cecum to Rectum with Synthetic Substitute, Endo', 375);
